
export default [


	{name: `Podawacz ścierki`, ext: '', list: ['',''], desc: '', type: 'specific role'},
	{name: `Naciskacz kleju żeby wypłynął`, ext: '', list: ['',''], desc: '', type: 'specific role'},
	{name: `Obracacz szczoteczki do zębów`, ext: '', list: ['',''], desc: '', type: 'specific role'},
	{name: `Odkręcacz pasty do zębów`, ext: '', list: ['',''], desc: '', type: 'specific role'},
	{name: `Wyciągacz tabletek`, ext: '', list: ['',''], desc: '', type: 'specific role'},
	{name: `Przyglądacz się czy obrazy wiszą równo`, ext: '', list: ['',''], desc: '', type: 'specific role'},
	{name: `Dostawiacz trzeciego krzesła w pokoju`, ext: '', list: ['',''], desc: '', type: 'specific role'},
	{name: `Rozwijacz rolki papieru`, ext: '', list: ['',''], desc: '', type: 'specific role'},
	{name: `Rozgniatacz truskawek za pomocą packi na muchy`, ext: '', list: ['',''], desc: '', type: 'specific role'},
	{name: `Ratownik piłkarzy, którzy w latach 1995-2000 byli kamieniarzami`, ext: '', list: ['',''], desc: '', type: 'specific role'},
	{name: `Bandażysta trucicieli szczurów, którzy dokładnie 345 dni temu mieli przeszczep lewego kciuka`, ext: '', list: ['',''], desc: '', type: 'specific role'},
	{name: `Scrollownik facebooka`, ext: '', list: ['',''], desc: '', type: 'specific role'},
	{name: `Podłączacz kabli USB na trzy`, ext: '', list: ['',''], desc: '', type: 'specific role'},
	{name: `Naciskacz klawiatury głosowy`, ext: '', list: ['',''], desc: '', type: 'specific role'},
	{name: `Głośny czytacz artykułów lub książki`, ext: '', list: ['',''], desc: '', type: 'specific role'},
	
	
	
	{name: ``, ext: '', list: ['',''], desc: 'Zaczynacie w karczmie, nagle podchodzi do was zakapturzony koleś i oferuje nagrodę za schwytanie niebezpiecznej osoby', type: 'RPG plot'},
	
	{name: ``, ext: '', list: ['',''], desc: 'Trafiacie na bezludną wyspę gdzie jedynym miejscem do którego możeice dojść była jaskinia giganta. Jako że żyli z zabijania potworów jedynym co mogli uczynić było pozbyć się giganta, po walce 4 na 1 musieli obmyślić sposób jak wydostać się z wyspy, zdecydowali że pościnają pobliskie drzewa izbudują z nich łódkę, udało się uciec tylko dwójce gdyż część z nich straciła nogi a jeden umarł. Na drodze do domu trafił ich piorun i łódka się rozbiła, przez co nikt nie wrócił ostatecznie do domu.', type: 'RPG plot'},
	
	{name: `Katakumby`, ext: '', list: ['',''], desc: 'Poszliście do katakumb bo słyszeliście, że znajdują się tam skarby ale w trakcie ich przeszukiwania orientujecie się, że nie wiecie jak je opuścić. W dodatku czujecie że zbliża się do was niebezpieczeństwo.', type: 'RPG plot'},
	
	{name: ``, ext: '', list: ['',''], desc: 'Wracacie po nocy z imprezy, w mieście panuje cisza kiedy nagle latarnie zaczynają mrugać, część z nich gaśnie, nagle orientujecie się że w waszą stronę coś zmierza, po bliższym oglądzie okazuje się, że to wielkie porcelanowe lalki wielkości ludzi.', type: 'RPG plot'},
	{name: ``, ext: '', list: ['',''], desc: 'Płyniecie statkiem jako pasażerowie z punktu A do B, nagle budzicie się i nie ma załogi, zacyznacie chodzić i obserwujecie że pewne rzeczy dzieją się same, np. garnek zupy sam się miesza. Chodząc po statku za którymś razem decydujecie by wrócić do swojej kajuty, jednak chwilę potem budzicie się ponownie w swojej kajucie, wtedy też zaczynacie poruszać się po pokładzie trafiając dokładnie w miejsca które wcześniej obserwowaliście, co więcej robicie w nich to samo co wcześniej robiło się samo, zupełnie jakbyście byli sprawcami waszej wizji. Nasi bohaterowie ostatecznie zeszli z pokładu i zaczęli szukać kogoś kto mógł im wytłumaczyć te zjawiska, jednak zaraz zaczęła ścigać ich straż.', type: 'RPG plot'},
	
	{name: ``, ext: '', list: ['',''], desc: 'Zostajecie wysłani w ruiny miasta by odzyskać porzuconą technologię. W międzyczasie okazuje się, że jest to niebezpieczna substancja, której szuka również banda najemników innego typa, neurotoksyna powodowała paraliż z zachowaniem stanu świadomości.', type: 'RPG plot'},
	
	{name: ``, ext: '', list: ['',''], desc: 'Zostaliście wybrani przez swojego mistrza do specjalnego egzaminu na przyszłych wojowników, jednak dopiero ten ostateczny test ma potwierdzić waszą wartość i upewnić was, że podołacie przyszłym misjom. Wasz egzamin okazuje się jednak przerastać wasze oczekiwania a część przeciwników bez ostrzeżenia próbuję was unicestwić w co ciężko uwierzyć, by było wolą waszego mistrza. Nieustanne i coraz trudniejsze zagadki, pokoje pełne śmiertelnych pułapek to tylko część drogi, w końcu jednak okazuje się, że mistrz został podmieniony i na jego miejscu znajduje się demon, wasz odwieczny wróg, który teraz planuje na zawsze was uwięzić w labiryncie.', type: 'RPG plot'},
	
	{name: ``, ext: '', list: ['',''], desc: 'Grupka młodych chłopaków z osiedla dyskutuje zmianę stylu życia, dyskutują wybranie się na tajemniczy festiwal "Kambodża Nadaje" o którym dowiedzieli się z kilku pozbieranych na dworcu ulotek. Dyskutowali czy warto lecieć tak daleko po czym wspólnie zdecydowali, że chcą zmienić swoje życie i postanowili odlecieć najbliższym samolotem. Na drodze jednak staje im pewien huligan o pamiętliwym pseudonimie "Glaca", którego ku ich nieszczęściu spotykają na każdym kroku => na murku, przy aptece, na klatce schodowej, w windzie, w autobusie, samolocie...', type: 'RPG plot'},
	
	{name: ``, ext: '', list: ['',''], desc: 'Uczycie się w specjalnej szkole o wysokim profilu, korzystającej z nowoczesnych i często dziwacznych technologii. Czekacie sobie na lekcje z prof. Trebuszem ale ten się spóźnia, po chwili dostajecie info, że prof. Trebusz się rozchorował i zastępstwo poprowadzi wam dzisiaj prof. Pierdolec. Przychodzi na lekcje i pokazuje bulbulator, ciekawy wynalazek jednak po chwili proponuje coś znacznie bardziej odjechanego, mianowicie chce zrobić wycieczkę do najgłębszego piętra podziemnego laboratorium, gdzie ponoć dawno temu dokonywano eksperymentów na ludziach.', type: ''},
	
	{name: ``, ext: '', list: ['',''], desc: '', type: 'RPG plot'},
	{name: ``, ext: '', list: ['',''], desc: '', type: 'RPG plot'},
	{name: ``, ext: '', list: ['',''], desc: '', type: 'RPG plot'},
	
	{name: ``, ext: '', list: ['',''], desc: 'Wasza koleżanka była ostatni raz widziana w kwaterze', type: 'RPG plot'},
	
	
	
	
	
	{name: `zmiana pogody`, ext: '', list: ['zaczyna padać deszcz','słyszycie grzmot'], desc: '', type: 'Narration Cards'},
	{name: `mama woła na obiad`, ext: '', list: ['',''], desc: '', type: 'Narration Cards'},
	{name: `ustąp miejsca`, ext: '', list: ['',''], desc: '', type: 'Narration Cards'},
	{name: `znajdujesz przedmiot`, ext: '', list: ['gitara','kupa'], desc: '', type: 'Narration Cards'},
	{name: `spotykasz znajomego`, ext: '', list: ['',''], desc: '', type: 'Narration Cards'},
	{name: `postanawiasz`, ext: '', list: ['odejść','zacząć rozmowę', 'pomyśleć', 'iść spać'], desc: '', type: 'Narration Cards'},
	
	// {name: ``, ext: '', list: ['',''], desc: '', type: 'Narration Cards'},
	// {name: ``, ext: '', list: ['',''], desc: '', type: 'Narration Cards'},
	// {name: ``, ext: '', list: ['',''], desc: '', type: 'Narration Cards'},
	
	{name: `Kim chcemy być, Nasza droga i kierunek`, ext: '', list: ['',''], desc: '', type: 'tematy do prezentacja'},
	{name: `RANDOM czyli Prawdopodobieństwo i losowość`, ext: '', list: ['',''], desc: '', type: 'tematy do prezentacja'},
	{name: `Czym jest Kreatywność i jak być kreatywnym`, ext: '', list: ['',''], desc: '', type: 'tematy do prezentacja'},
	{name: `Design (wprowadzenie)`, ext: '', list: ['',''], desc: '', type: 'tematy do prezentacja'},
	{name: `Graficzny design, projektowanie znaków i obrazów`, ext: '', list: ['',''], desc: '', type: 'tematy do prezentacja'},
	{name: `Nasz świat i prawa nim rządzące`, ext: '', list: ['',''], desc: '', type: 'tematy do prezentacja'},
	{name: `Improwizacja (wprowadzenie)`, ext: '', list: ['',''], desc: '', type: 'tematy do prezentacja'},
	{name: `Jak lepiej się uczyć?`, ext: '', list: ['',''], desc: '', type: 'tematy do prezentacja'},
	{name: `Jak zapamiętywać, żeby pamiętać na zawsze?`, ext: '', list: ['',''], desc: '', type: 'tematy do prezentacja'},
	{name: `Dlaczego matematyka jest najpiękniejszą nauką?`, ext: '', list: ['',''], desc: '', type: 'tematy do prezentacja'},
	{name: `Metoda naukowa`, ext: '', list: ['',''], desc: '', type: 'tematy do prezentacja'},
	{name: `PATTERN - czyli wzory, które występują wszędzie`, ext: '', list: ['',''], desc: '', type: 'tematy do prezentacja'},
	{name: `Czy można stworzyć własny świat?`, ext: '', list: ['',''], desc: '', type: 'tematy do prezentacja'},
	{name: `Jak utrudnić sobie życie?`, ext: '', list: ['',''], desc: '', type: 'tematy do prezentacja'},
	{name: `EMERGENCE - najważniejsza zasada wszechświata`, ext: '', list: ['',''], desc: '', type: 'tematy do prezentacja'},

	{name: `Rzeczy które bardzo chcielibyście robić ale z jakiegoś powodu boicie się spróbować.`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czy myślałeś(aś) już gdzie chcesz się znaleźć za 10 lat?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czy odczuwasz zazdrość, widząc, że innym wychodzi coś lepiej niż tobie.`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Lubisz improwizować?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czy jestem zbyt poważny?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Co aktualnie przebiega w waszych głowach?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Najbardziej stresujące doświadczenie w waszym życiu?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Co jest dla Was najbardziej bolesnym doświadczeniem?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Rozczarowanie ludzi którzy najbardziej na Ciebi liczyli`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Gdybyście mogli wybrać którą piosenkę miałbym śpiewać?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jaka była wasza najbardziej stresująca sytuacja w życiu?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Gdybyś dowiedział sie, że ktoś dla Ciebie ważny ma nieuleczalną chorobę i umrze za rok, czy powiedziałbyś mu to, czy raczej trzymał w przekonaniu, że wszystko jest dobrze?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jaką supermoc byś wybrał ze znanych Tobie?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jeśli mógłbyś manipulować prawami fizyki, które z nich byś zmienił?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czy większość ludzi wydaje się być głupsza czy może mądrzejsza od ciebie?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Dlaczego 2,3,4,x to wyjątkowa lub magiczna liczba?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Oglądasz czasem telewizję?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jakie są twoje najwcześniejsze wspomnienia z dzieciństwa jakie możesz przypomnieć?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jak często się kłócisz, częściej kłócisz się z rodzicami czy z kolegami?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Uważasz się za kogoś wyjątkowego?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Co myślisz o teorii płaskiej Ziemii?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Lubisz pająki? Uważasz, że one lubią Ciebie?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Posiadasz magiczny pilot, który może sterować ludźmi na odległość, jak go użyjesz?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jak można zostać stabliczkowanym?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Ile rolek papieru zużywasz średnio w ciągu tygodnia?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czy fejsbuk jest dobry dla zdrowia, czy powinien przestać istnieć?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jakie jest twoje najlepsze wspomnienie z dzieciństwa?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jeśli dostałbyś szansę na powtórzenie swojego życia, czy przeżyłbyś je inaczej?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jak się poznaliście, poznałeś z (wybierz osobę)?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jaka jest twoja ulubiona muzyka?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jeśli mógłbyś podróżować wszędzie, gdzie byś poleciał i dlaczego?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jeżeli mógłbyś zatrzymać ze sobą tylko 3 rzeczy, czym by one były?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czym nauczyciel w szkole wywarł na tobie największe wrażenie i dlaczego?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Co byś pragnął by było napisane na twoim nagrobku?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jaki moment w życiu uważasz, za najbardziej wpływowy?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Kim byś chciał zostać w przyszłości (lub dlaczego wybrałeś tę profesję?)`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jak spędzasz swój czas wolny?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jeśli wygrałbyś na loterii, jakich zmian dokonałbyś w swoim życiu?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Kogo najbardziej podziwiasz?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jakie są twoje trzy ulubione książki i dlaczego?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czego najbardziej się boisz, lękasz?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czym jest dla Ciebie miłość?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Co jest twoją najsilniejszą cechą osobowości?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jaki był twój najbardziej zawstydzający moment?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Gdybyś został wybrany prezydentem, co byś zrobił w pierwszej kolejności?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jeżeli mógłbyś doświadczyć dowolnego wydarzenia z przeszłości, teraźniejszości lub przyszłości to jakie by ono było?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czym jest umiejętność, którą najbardziej pragnąłbyś posiąść, nauczyć się?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jak według ciebie wyglądałby dzień idealny?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jak opisali by ciebie twoi znajomi?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Dlaczego ludzie ze sobą walczą?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Co i dlaczego sprawia, że się śmiejemy?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jakie wymówki używasz by się wykręcić od roboty, której nie lubisz?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Osoba, której ufasz ponad wszystko, i dlaczego?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Często płaczesz?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Możesz przywrócić jedną osobę do życia, kto to by był?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Możesz odzyskać jedną utraconą rzecz, co wybierasz?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Możesz cofnąć czas i przeżyć wszystko jeszcze raz, robisz to czy zostajesz przy obecnym?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czy napawdę nic nie istnieje bez potrzeby?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Gdzie byś się udał mając darmowy bilet na dowolny lot?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Dlaczego jesteś tym, kim jesteś?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jesteś osobą raczej otwartą na ludzi czy może zamkniętą w swoim świecie?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Łatwo nawiązujesz nowe znajomości?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Często myślisz za dużo?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Uważasz że lubisz się popisywać?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Dlaczego tu jesteś (na warsztatach)?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czy na warsztaty zdecydowałeś się sam(a) czy może ktoś Cię nakłaniał?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `W jakich klimatach najbardziej gustujesz (genres: fantasy, sci-fi, dzisiejsze)`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Kto Cię inspiruje, napisz kilka osobowości`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Wymień artystów których słuchasz lub oglądasz`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Ulubiony film/anime to...`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Wymień w kolejności co najbardziej lubisz robić`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jakiej muzyki słuchasz najczęściej, możesz napisać dlaczego...`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Nowe technologie Ci odpowiadają czy wolałbyś się cofnąć to dawnych lat?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czy wszystko co istnieje można sobie wyobrazić?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jakie jest twoje najlepsze wspomnienie z dzieciństwa?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jeśli dostałbyś szansę na powtórzenie swojego życia co byś zrobił inaczej?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jak się poznaliście poznałeś z (x)? (pytanie czasem wymaga dwóch osób)`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Z czego czujesz się najbardziej dumny?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jaka jest twoja ulubiona muzyka?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jeśli mógłbyś podróżować wszędzie gdzie byś poleciał i dlaczego?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jeżeli mógłbyś zatrzymać ze sobą tylko 3 rzeczy czym by one były?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czym nauczyciel w szkole wywarł na tobie największe wrażenie i dlaczego?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Co byś pragnął by było napisane na twoim nagrobku?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jaki moment w życiu uważasz za najbardziej wpływowy?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Kim byś chciał zostać w przyszłości (lub dlaczego wybrałeś tę profesję?)`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jak spędzasz swój czas wolny?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jeśli wygrałbyś na loterii jakich zmian dokonałbyś w swoim życiu?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Kogo najbardziej podziwiasz?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jakie są twoje trzy ulubione książki i dlaczego?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czego najbardziej się boisz lękasz?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czym jest dla Ciebie miłość?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Co jest twoją najsilniejszą cechą osobowości?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jaki był twój najbardziej zawstydzający moment?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Gdybyś został wybrany prezydentem co byś zrobił w pierwszej kolejności?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Na ile lat się czujesz obecnie (umysłowo) i dlaczego tak uważasz?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `czy czujesz się dojrzały?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jeżeli mógłbyś doświadczyć dowolnego wydarzenia z przeszłości teraźniejszości lub przyszłości to jakie by ono było?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czym jest umiejętność którą najbardziej pragnąłbyś posiąść nauczyć się?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jak według ciebie wyglądałby dzień idealny?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jak opisali by ciebie twoi znajomi?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Dlaczego ludzie ze sobą walczą?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Co i dlaczego sprawia że się śmiejemy?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jakie wymówki używasz by się wykręcić od roboty której nie lubisz?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Osoba której ufasz ponad wszystko i dlaczego?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Często płaczesz?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Możesz przywrócić jedną osobę do życia kto to by był?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Możesz odzyskać jedną utraconą rzecz co wybierasz?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Możesz cofnąć czas i przeżyć wszystko jeszcze raz robisz to czy zostajesz przy obecnym?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Kiedy ostatnio skłamałeś i z czym miało to związek?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Co najczęściej robisz, kiedy jest Ci niedobrze ze sobą?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jak oceniłbyś siebie jako osobę?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jak przedstawiłbyś siebie w 3 słowach?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Co jest ważniejsze, emocje czy logika?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Gdybyś mógł należeć do pewnej grupy lub drużyny, gdzie chciałbyś się znaleźć?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Ile razy czułeś się w życiu upokorzony?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czy może istnieć coś, czego nie rozumiesz?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czy można wiedzieć wszystko?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Gdzie najłatwiej można znaleźć nowych przyjaciół?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Gdyby krew była różowa, łatwiej byłoby Ci na nią patrzeć?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czy grawitacja jest potrzebna do życia?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Dlaczego życie nie jest łatwe?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Lubisz słuchać bajek i opowieści? Dlaczego?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Ulubiona bajka z dzieciństwa`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Gdzie uważasz, że się wychowałeś tak naprawdę?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Zdarzyło Ci sie kiedyś coś ukraść?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Gdyby świat miał się zakończyć jutro, jak spędziłbyś ostatni dzień życia?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Pragniesz pójść bardziej w stronę sztuki i emocji czy nauki i komputerów?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Która według Ciebie zasada powinna być uznana za najważniejszą?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jaki jest twój ulubiony zespół lub artysta?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jak widzisz siebie za 5-10 lat?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Co robisz kiedy jesteś znudzony?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Kim jest Twój największy bohater i dlaczego?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czy masz jakiś ulubiony film?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jakie rzeczy czynią Cię prawdziwie szczęśliwym?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `W jaki sposób radzisz sobie ze stresem?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Co lubisz robić dla zabawy, dla zabicia czasu?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Lubisz czytać?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Często śnisz? Jaki temat przytrafia Ci się najczęściej?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `O czym najczęściej marzysz?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Co czyni Cię złym i dlaczego?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czego najbardziej się boisz?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Masz jakiś ulubiony kolor?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Ulubiona gra, zabawa podwórkowa?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Co Cię na codzień śmieszy?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Co myślisz o prześladowaniu (szkoła)?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Wierzysz w prawdziwą przyjaźń lub miłość?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Myślałeś kiedyś kim chcesz być w przyszłości?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Myślałeś, by kiedyś wziąć ślub?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Uważasz się za osobę religijną lub uduchowioną?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Co chciałbyś wiedzieć, czego teraz nie wiesz, nie rozumiesz?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jakie przedmioty szkolne najbardziej Cię fascynują?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Uważasz się bardziej za introwertyka (osobę zamkniętą w sobie) czy ekstrawertyka (osobę otwartą i przebojową)`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Uważasz, że jesteś bardziej kreatywnie myślący, czy raczej praktyczny?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jak ważna jest dla Ciebie rodzina?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Co najbardziej Cię motywuje do pracy?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Łatwo przychodzi Tobie zawiązywanie nowych przyjaźni?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Twoja ulubiona książka?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czy czujesz się leniem, jak często odkładasz na potem?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czujesz się już dojrzały i odpowiedzialny, uważasz, że powinieneś być oficjalnie dorosły?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Gdybyś mógł raz cofnąć się w czasie, do jakiej epoki byś podróżował?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Twoja ulubiona gra, w którą uwielbiasz grać?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czy masz prawdziwych przyjaciół?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Kto jest Twoim najlepszym przyjacielem?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Masz jakiś wzór do naśladowania, autorytet?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Co myślisz o kolczykach i tatuażach?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jakie są Twoje cele na ten rok?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jaka cecha zawstydza Cię u Twoich rodziców?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Masz jakieś ulubione tradycje rodzinne?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jakie wydarzenia i spotkania rodzinne najbardziej lubisz przeżywać?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czy wspólny posiłek przy stole z rodziną to dla Ciebie ważne wydarzenie?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jakie cechy podziwiasz u innych ludzi?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jak byś opisał swoją osobowość?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czy w twojej szkole tworzą się małe grupki wspólnych poglądów, często dokuczając innym?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Kim jest twój ulubiony nauczyciel?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czy inni uczniowie oszukują na testach? Jaki jest twój pogląd na to?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czy byłeś kiedyś na randce? Czy twoi koledzy ze szkoły chodzą na randki?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jakich cech doszukiwałbyś się u potencjalnego partnera?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Chciałbyś pójść z kimś na randkę, czujesz się na to gotowy?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Masz jakieś zwierzątko domowe? Starasz się dbać o nie, lubisz je?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Twój ulubiony przepis rodzinny?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Ważne jest dla ciebie bycie sprawnym fizycznie, regularnie trenować ciało?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `O czym najczęściej myślisz za dnia?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Kto myślisz, że zna ciebie najlepiej? learn?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Uważasz, że umiejętność posługiwanie się językiem obcym jest istotna? Czy jest jakiś język, którego pragniesz się uczyć?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Myślisz, że ludzie oglądają zbyt wiele telewizji?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Co myślisz o polityce?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Istotne dla ciebie jest mieć prawo głosu?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czego twoim zdaniem powinno być więcej w szkole?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czego twoim zdaniem powinno być mniej w szkole?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jaką dodatkową aktywność chciałbyś zobaczyć poza programem szkolnym?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Kto jest najzabawniejszą osobą jaką znasz, i dlaczego?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jeśli mógłbyś, to pragnąłbyś być bardziej podobny do jakiej osoby?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Gdybyś mógł, to wybrałbyś sobie inne imię?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czy jest coś, co chciałbyś o mnie głębiej wiedzieć?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Co myślisz o statusie społecznym i popularności?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Myślisz, że w porządku jest kłamać? Jak często Ci się zdarza skłamać, uważasz, że kłamstwo można wytłumaczyć w pewnych przypadkach?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czy pamiętasz swoje sny?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jak ważny w życiu twoim zdaniem jest wygląd fizyczny?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Co czyni osobę dobrym przyjacielem?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Uważasz, że masz w sobie jakieś złe nawyki?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Chciałbyś być sławny?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czy byłeś kiedyś obiektem żartów w szkole?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czy bywasz zazdrosny o pewne rzeczy, jeśli tak, to jakie? Jak sobie radzisz z tymi emocjami?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Chciałbyś mieć kiedyś dzieci?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jaka aktywność sportowa cię interesuje?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jakie doświadczenia uważasz, że wpłynęły na twoje życie najbardziej?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jeśli wygrałbyś na loterii, jak wydałbyś te pieniądze?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Najpiękniejsze wspomnienia z dzieciństwa?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jakie podjęte decyzje nauczyły cię najwięcej?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jakie jest twoje najwcześniejsze wspomnienie z życia?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jeśli mógłbyś spotkać kogokolwiek, również ze świata martwych, kto by to był?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Co uważasz oznacza być płci męskiej a żeńskiej`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jakie zwierzę oddaje cię najlepiej?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czy uważasz, że się hamujesz, nie wykorzystując pełni swojego potencjału?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jak chciałbyś zostać zapamiętany?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Uważasz, że masz zdolności przywódcze?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Jak uważasz, że wyglądałby dzień doskonały?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	{name: `Czy byłeś kiedyś świadkiem wypadku?`, ext: '', list: ['',''], desc: '', type: 'pytania'},
	
	
	
	
	{ name: 'pieczeń technologiczna', desc: '', type: 'generated'},
	{ name: 'opublikować militarny papieros', desc: '', type: 'generated'},
	{ name: 'jednoroczny rządowy stolec', desc: '', type: 'generated'},
	{ name: 'szorstki dziecięcy technik', desc: '', type: 'generated'},
	{ name: 'rumuńskie grosze', desc: '', type: 'generated'},
	{ name: 'niewzruszona pomarańcza', desc: '', type: 'generated'},
	{ name: 'farbować dupę', desc: '', type: 'generated'},
	{ name: 'Niezdecydowany Michał', desc: '', type: 'generated'},
	{ name: 'gorący lider', desc: '', type: 'generated'},
	{ name: 'ukośna wieprzowina', desc: '', type: 'generated'},
	{ name: 'ugryźć kąt prosty', desc: '', type: 'generated'},
	{ name: 'uzbrojony biznes', desc: '', type: 'generated'},
	{ name: 'brzozowa maniera', desc: '', type: 'generated'},
	{ name: 'rządowa licencja na saksofon', desc: '', type: 'generated'},
	{ name: 'praktycznie parzysty wyszukany wynalazca', desc: '', type: 'generated'},
	{ name: 'ochrzcić Nową Zelandię', desc: '', type: 'generated'},
	{ name: 'kasta brazylijska', desc: '', type: 'generated'},
	{ name: 'afgańska gałka muszkatałowa', desc: '', type: 'generated'},
	{ name: 'uniwersytet pornograficzny', desc: '', type: 'generated'},
	{ name: 'obierać wietnamską jagodę', desc: '', type: 'generated'},
	{ name: 'chamski alpinizm', desc: '', type: 'generated'},
	{ name: 'operować ducha', desc: '', type: 'generated'},
	{ name: 'turowy makaron', desc: '', type: 'generated'},
	{ name: 'deklaracja odpadów', desc: '', type: 'generated'},
	{ name: 'gałka obserwacyjna - oko', desc: '', type: 'generated'},
	{ name: 'Mrucząca forteca i zbawienie prostokąta', desc: '', type: 'generated'},
	{ name: 'zwiększyć kontekst nadgarska', desc: '', type: 'generated'},
	{ name: 'kaplica gumy do żucia', desc: '', type: 'generated'},
	{ name: 'poddać się w liczbie pojedynczej', desc: '', type: 'generated'},
	{ name: 'beżowa agresja', desc: '', type: 'generated'},
	{ name: 'zwyczajowy zrzucacz sterowania', desc: '', type: 'generated'},
	{ name: 'zacofany bramkarz', desc: '', type: 'generated'},
	{ name: 'syryjski per laser', desc: '', type: 'generated'},
	{ name: 'gust to torturować filologa', desc: '', type: 'generated'},
	{ name: 'nieprawdziwa drzemka', desc: '', type: 'generated'},
	{ name: 'samodzielnie mineralny', desc: '', type: 'generated'},
	{ name: 'luksusowy pionowo', desc: '', type: 'generated'},
	{ name: 'Abraham gol mizerny', desc: '', type: 'generated'},
	{ name: 'hydraulicznie ukośne suminie', desc: '', type: 'generated'},
	{ name: 'nieobecny wieszak', desc: '', type: 'generated'},
	{ name: 'jakiż ty jałowy i rowerowy', desc: '', type: 'generated'},
	{ name: 'szczegółowo sfałszowany', desc: '', type: 'generated'},
	{ name: 'elektromagnetyczna miłość', desc: '', type: 'generated'},
	{ name: 'nieunikniona łacina', desc: '', type: 'generated'},
	{ name: 'kurdyjski zodiak', desc: '', type: 'generated'},
	{ name: 'harmonijna zarozumiałość', desc: '', type: 'generated'},
	{ name: 'wypalać majtki to liliowy obyczaj, ale można doświadczyć skurczów', desc: '', type: 'generated'},
	{ name: 'zapinać schemat - lecieć po schemacie cały czas', desc: '', type: 'generated'},
	{ name: 'łaskotać puch seksowny', desc: '', type: 'generated'},
	{ name: 'spontaniczna sauna wegetariańska', desc: '', type: 'generated'},
	{ name: 'niezdecydowany bukiet NATO', desc: '', type: 'generated'},
	{ name: 'grubiańska gwarancja rodzeństwa', desc: '', type: 'generated'},
	{ name: 'Pułkownik Rosół', desc: '', type: 'generated'},
	{ name: 'Major Ruskie Dziąsło', desc: '', type: 'generated'},
	{ name: 'Autobusowa panika', desc: '', type: 'generated'},
	{ name: 'Pokojówka-Proboszcz', desc: '', type: 'generated'},
	{ name: 'obrzezanie Organizacja Narodów Zjednoczonych', desc: '', type: 'generated'},
	{ name: 'psychologiczna krewetka', desc: '', type: 'generated'},
	{ name: 'wyciskać okienko', desc: '', type: 'generated'},
	{ name: 'celebrować wróżbę', desc: '', type: 'generated'},
	{ name: 'biseksualny kieszonkowiec redaktor', desc: '', type: 'generated'},
	{ name: 'TT - teraźniejsza teściowa', desc: '', type: 'generated'},
	{ name: 'obrus PRECZ! - alternatywne zaklęcie do stoliczku nakryś się i CZAS STOP!', desc: '', type: 'generated'},
	{ name: 'szokująca ramka kończyny', desc: '', type: 'generated'},
	{ name: 'nieoczekiwana wieprzowina', desc: '', type: 'generated'},
	{ name: 'Andrzej Dowcipny', desc: '', type: 'generated'},
	{ name: 'profesjonalny uchodźca', desc: '', type: 'generated'},
	{ name: 'ironiczna piekarnia', desc: '', type: 'generated'},
	{ name: 'wyprowadzać chwasty', desc: '', type: 'generated'},
	{ name: 'pogodny magnetyzm', desc: '', type: 'generated'},
	{ name: 'autograf czołowy', desc: '', type: 'generated'},
	{ name: 'zabytek cieplny', desc: '', type: 'generated'},
	{ name: 'pantera-wiedźma', desc: '', type: 'generated'},
	{ name: 'despotyczny katolicyzm', desc: '', type: 'generated'},
	{ name: 'konstytucyjne spożywanie wyciągu na strychu', desc: '', type: 'generated'},
	{ name: 'żarliwa banda biskupów', desc: '', type: 'generated'},
	{ name: 'służbowa brzytwa', desc: '', type: 'generated'},
	{ name: 'protokół wspinaczkowy', desc: '', type: 'generated'},
	{ name: 'szczery spisek', desc: '', type: 'generated'},
	
	{ name: 'Mów BaRDZo wyraźnie (aż za wyraźnie)', desc: '', type: 'status'},
	{ name: 'Mów jak jaskiniowiec, nie odmieniaj przez przypadki (ja jeść, pić, zrobić to i tamto)',  desc: '', type: 'status'},
	{ name: 'Czwarta Gęstość', desc: '', type: 'status'},
	{ name: 'Schmizm - schmi cały czaschm', desc: '', type: 'status'},
	{ name: 'Rymowanie w komunikacji', desc: '', type: 'status'},
	{ name: 'Pijaństwo (wiadomix)', desc: '', type: 'status'},
	{ name: 'Robot (bez intonacji--emocji, ruchy sztywne, metaliczne)', desc: '', type: 'status'},
	{ name: 'Zombie mode ( buczenie gibberish)', desc: '', type: 'status'},
	{ name: 'Ogłupienie ( bądź koprem)', desc: '', type: 'status'},
	{ name: 'Zauroczenie - hipnoza', desc: '', type: 'status'},
	{ name: 'Śpiewaj zamiast mówić', desc: '', type: 'status'},
	{ name: 'Spontaniczne śpiewanie fragmentów piosenek', desc: '', type: 'status'},
	{ name: 'Robienie głupich min / nienaturalne emocje', desc: '', type: 'status'},
	{ name: 'Śmiechawka (nie można powstrzymać beczki - dobre na zdychaido)', desc: '', type: 'status'},
	{ name: 'Mądrala, Głupek, Śmieszek (opowiada dowcipy Sztrasburgera)', desc: '', type: 'status'},
	{ name: 'Artysta (rozmawia językiem tak literackim że niezrozumiałym dla zwykłych śmiertelników)',  desc: '', type: 'status'},
	{ name: 'Gbur-Dupek (jest niemiły aż do bólu)', desc: '', type: 'status'},
	{ name: 'Miluszek (jest wręcz za miły i w kółko wszystkich pyta czy może w czymś pomóc)', desc: '', type: 'status'},
	{ name: 'Introvert, Autism, Non-werbal, Neurotic, Czepialski', desc: '', type: 'status'},
	{ name: 'Creepy smile man (uśmiecha się jakby już chciał poderżnąć ci gardło ale tego nie robi)',  desc: '', type: 'status'},
	{ name: 'Creepy look (patrzy się na wszystkich “wilkiem” budząc przerażenie)', desc: '', type: 'status'},
	{ name: 'Padaczka-Man (ma ciągłe drgawki lub co jakiś czas mu sie załącza atak) małcim dlaszego',  desc: '', type: 'status'},
	{ name: 'Zmienniś (nastrój zmienia się co chwila)', desc: '', type: 'status'},
	{ name: 'Zoomer (gadałby tylko o gierkach i levelach jakie nawbijał ostatnio w fortnajcie)',  desc: '', type: 'status'},
	{ name: 'Boomer (doradza wszystkim jak mają żyć według swoich archaicznych metod)', desc: 'Za moich czasów to takie rzeczy załatwiało się inaczej...', type: 'status'},
	{ name: 'Tylny Dyskutant (rozmawiając z tobą jest zawsze zwrócony tyłkiem do ciebie)', desc: '', type: 'status'},
	{ name: 'Cringer-Melanista', desc: '', type: 'status'},
	{ name: 'Włosozaplatacz', desc: 'ej. a mogę ci zapleść warkocza?', type: 'status'},
	{ name: 'Corobiec', desc: 'Co robisz? Ej a co będziemy teraz robić?', type: 'status'},
	// { name: 'Jakwodzista', desc: '', type: 'status'},
	{ name: 'Storykjubista', desc: '', type: 'status'},
	{ name: 'Trener motywacyjna', desc: '', type: 'status'},
	
	{ name: 'aura', type: 'supermoce'},
	{ name: 'regeneracja', type: 'supermoce'},
	{ name: 'zaklinanie', type: 'supermoce'},
	{ name: 'transmutacja', type: 'supermoce'},
	{ name: 'zmiana kształtu', type: 'supermoce'},
	{ name: 'replikacja', type: 'supermoce'},
	{ name: 'jasnowidzenie', type: 'supermoce'},
	{ name: 'niewidzialność', type: 'supermoce'},
	{ name: 'widzenie w ciemności', type: 'supermoce'},
	{ name: 'lewitacja', type: 'supermoce'},
	{ name: 'latanie', type: 'supermoce'},
	{ name: 'telekineza', type: 'supermoce'},
	{ name: 'telepatia', type: 'supermoce'},
	{ name: 'teleportacja', type: 'supermoce'},
	{ name: 'krzyk śmierci', type: 'supermoce'},
	{ name: 'przywoływanie stworzeń', type: 'supermoce'},
	
	{ name: 'uzdrowienie', type: 'supermoce'},
	{ name: 'zamiana umysłów', type: 'supermoce'},
	{ name: 'polimorfizm', type: 'supermoce'},
	{ name: 'petryfikacja', type: 'supermoce'},
	{ name: 'nieśmiertelność', type: 'supermoce'},
	{ name: 'hipnoza', type: 'supermoce'},
	{ name: 'nekromancja', type: 'supermoce'},
	{ name: 'zauroczenie zwierzęcia', type: 'supermoce'},
	{ name: 'emisja promieniowania', type: 'supermoce'},
	{ name: 'paraliż', type: 'supermoce'},
	{ name: 'kontrolowanie pamięci', type: 'supermoce'},
	{ name: 'kontrolowanie snów', type: 'supermoce'},
	{ name: 'paraliżowanie', type: 'supermoce'},
	{ name: 'pranie mózgu', type: 'supermoce'},
	// { name: 'komunikacja ze zwierzętami', type: 'supermoce'},
	
	{ name: 'super przyczepność', type: 'supermoce'},
	{ name: 'oddychanie pod wodą', type: 'supermoce'},
	{ name: 'chodzenie po wodzie', type: 'supermoce'},
	{ name: 'bariera', type: 'supermoce'},
	{ name: 'kradzież supermocy', type: 'supermoce'},
	{ name: 'tworzenie iluzji w umyśle', type: 'supermoce'},
	{ name: 'kontrola umysłu', type: 'supermoce'},
	{ name: 'opętanie', type: 'supermoce'},
	{ name: 'kontrola pogody', type: 'supermoce'},
	{ name: 'manipulacja prawami fizyki', type: 'supermoce'},
	{ name: 'manipulacja światłem', type: 'supermoce'},
	{ name: 'manipulacja temperaturą', type: 'supermoce'},
	{ name: 'manipulacja magnetyzmem', type: 'supermoce'},
	{ name: 'manipulacja grawitacją', type: 'supermoce'},
	{ name: 'materializacja obiektów', type: 'supermoce'},
	{ name: 'ożywienie narysowanych rzeczy', type: 'supermoce'},
	
	{ name: 'szpony', type: 'supermoce'},
	{ name: 'kolce i rogi', type: 'supermoce'},
	{ name: 'ciernie', type: 'supermoce'},
	{ name: 'macki', type: 'supermoce'},
	{ name: 'manipulacja włosami', type: 'supermoce'},
	{ name: 'przechodzenie przez ściany', type: 'supermoce'},
	
	{ name: 'manipulacja czasem', type: 'supermoce'},
	{ name: 'przemieszczanie się w czasie', type: 'supermoce'},
	{ name: 'unieruchomienie', type: 'supermoce'},
	{ name: 'spowolnienie', type: 'supermoce'},
	
	{ name: 'ożywienie zwłok', type: 'supermoce'},
	{ name: 'wskrzeszenie robaków', desc: 'robaki mogą pożerać inne rzeczy a trawiąc je dają posiadaczowi dodakową energię', type: 'supermoce'},
	{ name: 'łzy kwasowe', tag: 'cry, drop, water', type: 'supermoce'},
	{ name: 'kwas zamiast krwi', type: 'supermoce'},
	{ name: 'moc błyskawic', type: 'supermoce'},
	{ name: 'moc trucizn', type: 'supermoce'},
	{ name: 'moc ognia', type: 'supermoce'},
	{ name: 'moc lodu', type: 'supermoce'},
	{ name: 'moc wody', type: 'supermoce'},

	{ name: 'super precyzja', type: 'supermoce'},
	{ name: 'super odwaga', type: 'supermoce'},
	{ name: 'kontrola emocji', type: 'supermoce'},
	{ name: 'super szybkość', type: 'supermoce'},
	{ name: 'super refleks', type: 'supermoce'},
	
	{ name: 'odporność na promieniowanie', type: 'supermoce'},
	{ name: 'odporność na żywioły', type: 'supermoce'},
	{ name: 'odporność na trucizny', type: 'supermoce'},
	{ name: 'odporność na choroby', type: 'supermoce'},
	{ name: 'super wytrzymałość', type: 'supermoce'},
	{ name: 'super zmysły', type: 'supermoce'},
	{ name: 'super siła', type: 'supermoce'},

	{ name: 'kontrola cieni', type: 'supermoce'},
	
	{ name: 'Słoniowacizna',
		desc: 'Choroba powodowana przez pasożyta przenoszonego przez komary lub wady genetyczne, zarażonemu dana część ciała okropnie przerasta, przybierając przy tym monstrualną wielkość',
		type: 'choroby'
	},
	{ name: 'Pica', desc: 'Osoba chora  je rzeczy niejadalne',
		type: 'choroby'
	},
	{ name: 'Analgezja',
		desc: ' osoba nie czuje bólu, głodu ani senności , przez to ulega poparzeniom, skaleczeniom i urazom nawet nie zdając sobie sprawy z powagi sytuacji.',
		type: 'choroby'
	},
	{ name: 'Trichotillomania ',
		desc: ' osoba chora impulsywnie wyrywa sobie włosy po czym w niektórych przypadkach je zjada, w jej żołądku tworzą się trichobezoary (kulki włosów) które są niemożliwe do strawienia i trzeba usuwać je operacyjnie. Choroba występuje najczęściej u dzieci i ma podłoże psychiczne.',
		type: 'choroby'
	},
	{ name: 'Zespół Unera Tana  ',
		desc: ' osoba chora umie chodzić tylko na czworaka, jest zacofana w rozwoju i posługuje się prymitywną mową.',
		type: 'choroby'
	},
	{ name: 'Rumień wędrujący ciała (język geograficzny)',
		desc: ' przez stres lub wrażliwość skóry na języku pojawiają się esy floresy zwane wyspami. Choroba nieszkodliwa ale może powodować dyskomfort przy spożywaniu ostrych i kwaśnych rzeczy.',
		type: 'choroby'
	},
	{ name: 'Rogi u ludzi ',
		desc: ' niezłośliwy nowotwór skóry powoduje że osobie chorej na głowie zaczynają sie formować rogi, co prawda nie są takie ładne i kształtne jak u kóz na przykład ale mocno je przypominają.',
		type: 'choroby'
	},
	{ name: 'Vitiligo ',
		desc: ' genetyczna choroba powodująca że na skórze robią się zupelnie odbarwione miejsca wyglądające jak ogromne znamiona.',
		type: 'choroby'
	},
	{ name: 'Trimetyloaminuria ',
		desc: ' osoba śmierdzi rybą ciągle przez brak enzymu wpływającego na metabolizm. Zapach jest niezmywalny.',
		type: 'choroby'
	},
	{ name: 'Progopagnozja ',
		desc: ' osoba chora nie potrafi rozpoznawać twarzy nawet osób z którymi żyje na codzień, przyczyną mogą być geny lub urazy mózgu.',
		type: 'choroby'
	},
	{ name: 'Hipertrichomia ',
		desc: ' osoba chora ma bardzo bujne owłosienie na całym ciele, przez co często spotyka się z nazywaniem jej wilkołakiem.',
		type: 'choroby'
	},
	{ name: 'Bliźniak pasożytniczy ',
		desc: ' Osoba dotknięta przypadłością ma dodatkowe kończyny i całe części ciała należące do bliźniaka zupełnie od niej zależnego.',
		type: 'choroby'
	},
	{ name: 'Akinetopsja ',
		desc: ' osoba chora nie jest w stanie dostrzec ruchu, nie ma problemu z obserwacją statycznych przedmiotów ale gdy coś się ruszy zamienia się tylko w rozmytą plame lub statyczny obraz',
		type: 'choroby'
	},
	
	{ name: 'aktor', type:'zawody'},
	{ name: 'architekt', type:'zawody'},
	{ name: 'archeolog', type:'zawody'},
	{ name: 'aptekarz', type:'zawody'},
	{ name: 'administrator', type:'zawody'},
	{ name: 'astronom', type:'zawody'},
	{ name: 'budowniczy', type:'zawody'},
	{ name: 'bankier', type:'zawody'},
	{ name: 'barman', type:'zawody'},
	{ name: 'bejsbolista', type:'zawody'},
	{ name: 'chirurg', type:'zawody'},
	{ name: 'chemik', type:'zawody'},
	{ name: 'clown', type:'zawody'},
	{ name: 'cukiernik ', type:'zawody'},
	{ name: 'choreograf', type:'zawody'},
	{ name: 'charakteryzator', type:'zawody'},
	{ name: 'dermatolog', type:'zawody'},
	{ name: 'detektyw', type:'zawody'},
	{ name: 'dietetyk', type:'zawody'},
	{ name: 'doradca finansowy', type:'zawody'},
	{ name: 'elektryk', type:'zawody'},
	{ name: 'ekolog ', type:'zawody'},
	{ name: 'etnograf', type:'zawody'},
	{ name: 'egzorcysta ', type:'zawody'},
	{ name: 'ekonomista', type:'zawody'},
	{ name: 'fryzjer', type:'zawody'},
	{ name: 'fizjoterapeuta', type:'zawody'},
	{ name: 'fotograf', type:'zawody'},
	{ name: 'fecista', type:'zawody'},
	{ name: 'felietonista ', type:'zawody'},
	{ name: 'farmaceuta', type:'zawody'},
	{ name: 'grafik', type:'zawody'},
	{ name: 'ginekolog', type:'zawody'},
	{ name: 'gliniarz', type:'zawody'},
	{ name: 'grabarz', type:'zawody'},
	{ name: 'historyk', type:'zawody'},
	{ name: 'hydraulik', type:'zawody'},
	{ name: 'higienistka', type:'zawody'},
	{ name: 'ilustrator', type:'zawody'},
	{ name: 'iluzjonista', type:'zawody'},
	{ name: 'inspektor', type:'zawody'},
	{ name: 'informatyk', type:'zawody'},
	{ name: 'jubiler', type:'zawody'},
	{ name: 'kierownik', type:'zawody'},
	{ name: 'kamieniarz', type:'zawody'},
	{ name: 'lakiernik', type:'zawody'},
	{ name: 'lekarz', type:'zawody'},
	{ name: 'meblowy', type:'zawody'},
	{ name: 'maszynista', type:'zawody'},
	{ name: 'magazynier', type:'zawody'},
	{ name: 'nauczyciel', type:'zawody'},
	{ name: 'nurek', type:'zawody'},
	{ name: 'obserwator', type:'zawody'},
	{ name: 'operator', ext: 'koparki, wózka, maszyn', type:'zawody'},
	{ name: 'oficer', type:'zawody'},
	{ name: 'ogrodnik', type:'zawody'},
	{ name: 'pamiątkarz', type:'zawody'},
	{ name: 'piłkarz', type:'zawody'},
	{ name: 'piosenkarz', type:'zawody'},
	{ name: 'ratownik', type:'zawody'},
	{ name: 'recepcjonista', type:'zawody'},
	{ name: 'scenarzysta', type:'zawody'},
	{ name: 'siatkarz', type:'zawody'},
	{ name: 'sędzia', type:'zawody'},
	{ name: 'tatuażysta', type:'zawody'},
	{ name: 'technik', type:'zawody'},
	{ name: 'tancerz', type:'zawody'},
	{ name: 'urzędnik', type:'zawody'},
	{ name: 'ustawiacz', type:'zawody'},
	{ name: 'weterynarz', type:'zawody'},
	{ name: 'właściciel', type:'zawody'},
	{ name: 'wizytator / kontroler', type:'zawody'},
	{ name: 'wizażysta', type:'zawody'},
	{ name: 'zoolog', type:'zawody'},
	{ name: 'zegarmistrz', type:'zawody'},
	{ name: 'zakonnica', type:'zawody'},
	{ name: 'zarządca nieruchomości', type:'zawody' },
	
	// {name: 'Dlaczego grupki na Messengerze to generatory konflików?', type:'prezentacje'},
	// {name: 'Jak możemy pomóc ludziom?', type:'prezentacje'},

	{name: 'radość', tag: 'pozytywne', type:'emocje'},
	{name: 'wdzięczność', tag: 'pozytywne', type:'emocje'},
	{name: 'miłość', tag: 'pozytywne', type:'emocje'},
	{name: 'zaufanie', tag: 'pozytywne', type:'emocje'},
	{name: 'zainteresowanie', tag: 'pozytywne', type:'emocje'},
	{name: 'ciekawość', tag: 'pozytywne', type:'emocje'},
	
	{name: 'opanowanie', tag: 'neutralne', type:'emocje'},
	{name: 'dezorientacja', tag: 'neutralne', type:'emocje'},
	{name: 'zaskoczenie', tag: 'neutralne', type:'emocje'},
	
	{name: 'rozpacz', tag: 'negatywne', type:'emocje'},
	{name: 'wstyd', tag: 'negatywne', type:'emocje'},
	{name: 'zażenowanie', tag: 'negatywne', type:'emocje'},
	{name: 'gniew', tag: 'negatywne', type:'emocje'},
	// {name: 'wściekłość', tag: 'negatywne', type:'emocje'},
	{name: 'rozczarowanie', tag: 'negatywne', type:'emocje'},
	{name: 'zazdrość', tag: 'negatywne', type:'emocje'},
	{name: 'zawiść', tag: 'negatywne', type:'emocje'},
	{name: 'nienawiść', tag: 'negatywne', type:'emocje'},
	{name: 'pycha', tag: 'negatywne', type:'emocje'},
	{name: 'agresja', tag: 'negatywne', type:'emocje'},
	{name: 'samotność', tag: 'negatywne', type:'emocje'},
	{name: 'smutek', tag: 'negatywne', type:'emocje'},
	{name: 'strach', tag: 'negatywne', type:'emocje'},
	{name: 'uprzedzenie', tag: 'negatywne', type:'emocje'},
	{name: 'upokorzenie', tag: 'negatywne', type:'emocje'},

	{name: 'angielski', type:'język'},
	{name: 'hiszpański', type:'język'},
	{name: 'portugalski', type:'język'},
	{name: 'rosyjski', type:'język'},
	{name: 'niemiecki', type:'język'},
	{name: 'esperanto', type:'język'},
	{name: 'francuski', type:'język'},
	{name: 'duński', type:'język'},
	{name: 'fiński', type:'język'},
	{name: 'polski', type:'język'},
	{name: 'arabski', type:'język'},
	{name: 'somalijski', type:'język'},
	{name: 'suahili', type:'język'},
	
	{name: 'wielka szachownica', type:'miejsce'},
	{name: 'ptasie gniazdo', type:'miejsce'},
	{name: 'pajęczyna', type:'miejsce'},
	{name: 'ring bokserski', type:'miejsce'},
	{name: 'octagon MMA', type:'miejsce'},
	{name: 'skocznia', type:'miejsce'},
	{name: 'namiot', type:'miejsce'},
	{name: 'dojo', type:'miejsce'},
	{name: 'cyrk', type:'miejsce'},
	{name: 'biuro', type:'miejsce'},
	{name: 'studio tańca', type:'miejsce'},
	{name: 'legowisko smoka', type:'miejsce'},
	{name: 'dno oceanu', type:'miejsce'},
	{name: 'las elfów', type:'miejsce'},
	{name: 'diabelski młyn', type:'miejsce'},
	{name: 'sklep spożywczy', type:'miejsce'},
	{name: 'kuźnia', type:'miejsce'},
	{name: 'pole golfowe', type:'miejsce'},
	{name: 'helikopter', type:'miejsce'},
	{name: 'iglo', type:'miejsce'},
	{name: 'klub nocny', type:'miejsce'},
	{name: 'nibylandia', type:'miejsce'},
	{name: 'klatka', type:'miejsce'},
	{name: 'farma kangurów', type:'miejsce'},
	{name: 'biblioteka', type:'miejsce'},
	{name: 'księżyc', type:'miejsce'},
	{name: 'sklep ze zwięrzętami'},
	{name: 'podziemia', type:'miejsce'},
	{name: 'kopalnia', type:'miejsce'},
	{name: 'biały dom', type:'miejsce'},
	{name: 'dom wampira', type:'miejsce'},
	{name: 'kort tenisowy', type:'miejsce'},
	{name: 'boisko', type:'miejsce'},
	{name: 'kryjówka złodzieji', type:'miejsce'},
	{name: 'sala sądowa', type:'miejsce'},
	{name: 'dom opieki', type:'miejsce'},
	{name: 'izba wytrzeźwień', type:'miejsce'},
	{name: 'kabina biurowa', type:'miejsce'},
	{name: 'tor wyścigowy', type:'miejsce'},
	{name: 'obóz najemników', type:'miejsce'},
	{name: 'scena', type:'miejsce'},
	
	{name: 'galeria sztuki', type:'miejsce'},
	{name: 'Villa Hellena', type:'miejsce'},
	{name: 'kibel w szkole', type:'miejsce'},
	{name: 'sala lekcyjna', type:'miejsce'},
	{name: 'pokój nauczycielski', type:'miejsce'},
	{name: 'gabinet dyrektora', type:'miejsce'},
	{name: 'ślepa uliczka', type:'miejsce'},
	{name: 'pokój luster', type:'miejsce'},
	{name: 'szyb wentylacyjny', type:'miejsce'},
	{name: 'kanalizacja', type:'miejsce'},

	{name: 'blok mieszkalny', type:'miejsce'},
	{name: 'komisariat', type:'miejsce'},
	{name: 'sklep osiedlowy', type:'miejsce'},
	{name: 'centrum handlowe', type:'miejsce'},
	{name: 'zakład karny', type:'miejsce'},
	{name: 'myjnia samochodowa', type:'miejsce'},
	{name: 'drukarnia', type:'miejsce'},
	{name: 'fabryka (czegoś)', type:'miejsce'},
	{name: 'sypialnia', type:'miejsce'},
	{name: 'skarbiec', type:'miejsce'},
	{name: 'warsztat', type:'miejsce'},
	{name: 'port', type:'miejsce'},
	{name: 'lotnisko', type:'miejsce'},
	{name: 'bunkier', type:'miejsce'},

	{name: 'lodowiec', type:'miejsce'},
	{name: 'lodowisko', type:'miejsce'},
	{name: 'wesołe miasteczko', type:'miejsce'},
	{name: 'miasto', type:'miejsce'},
	{name: 'studnia', type:'miejsce'},
	{name: 'ocean', type:'miejsce'},
	{name: 'morze', type:'miejsce'},
	{name: 'basen', type:'miejsce'},
	{name: 'latarnia morska', type:'miejsce'},
	{name: 'wieża widokowa', type:'miejsce'},
	{name: 'wioska', type:'miejsce'},
	{name: 'dżungla', type:'miejsce'},
	{name: 'poligon wojskowy', type:'miejsce'},
	{name: 'wysypisko śmieci', type:'miejsce'},
	{name: 'rezydencja magnata', type:'miejsce'},
	{name: 'silos nuklearny', type:'miejsce'},
	{name: 'wodociągi', type:'miejsce'},
	{name: 'gorzelnia', type:'miejsce'},
	{name: 'piramida', type:'miejsce'},
	{name: 'grobowiec', type:'miejsce'},
	{name: 'świątynia', type:'miejsce'},
	{name: 'sala gimnastyczna', type:'miejsce'},
	{name: 'stołówka', type:'miejsce'},
	{name: 'muzeum', type:'miejsce'},

	{name: 'statek na wodzie', type:'miejsce'},
	{name: 'statek kosmiczny', type:'miejsce'},
	{name: 'stacja kosmiczna', type:'miejsce'},
	{name: 'wnętrze samolotu', type:'miejsce'},
	{name: 'wnętrze czołgu', type:'miejsce'},
	{name: 'łódź podwodna', type:'miejsce'},
	{name: 'blokowisko', type:'miejsce'},
	{name: 'wieś', type:'miejsce'},
	{name: 'pole', type:'miejsce'},

	{name: 'starożytna jaskinia', type:'miejsce'},
	{name: 'pustynia', type:'miejsce'},
	{name: 'piwnica', type:'miejsce'},
	{name: 'biegun', type:'miejsce'},
	{name: 'atlantyda', type:'miejsce'},
	{name: 'góry', type:'miejsce'},
	{name: 'las', type:'miejsce'},
	{name: 'moczary', type:'miejsce'},
	{name: 'zamek', type:'miejsce'},
	{name: 'sala tronowa', type:'miejsce'},
	{name: 'komnata na zamku', type:'miejsce', desc: 'fajne i mroczne miejsce, gdzie można rozegrać scenkę'},
	{name: 'lochy', type:'miejsce'},
	{name: 'cela śmierci', type:'miejsce'},
	{name: 'wyspa', type:'miejsce'},
	{name: 'laguna', type:'miejsce'},
	{name: 'szpital', type:'miejsce'},
	{name: 'karczma', type:'miejsce'},
	{name: 'uniwersytet', type:'miejsce'},
	{name: 'akademia', type:'miejsce'},
	{name: 'szkoła', type:'miejsce'},
	{name: 'chińska fabryka', type:'miejsce'},
	{name: 'katakumby', type:'miejsce'},
	{name: 'zoo', type:'miejsce'},
	{name: 'gułag', type:'miejsce'},
	{name: 'kreml', type:'miejsce'},
	{name: 'park', type:'miejsce'},
	{name: 'parking', type:'miejsce'},

	{name: 'morderstwo', type:'przestępstwa'},
	{name: 'oszustwo', type:'przestępstwa'},
	{name: 'wymuszenie', type:'przestępstwa'},
	{name: 'okup', type:'przestępstwa'},
	{name: 'przetrzymywanie', type:'przestępstwa'},
	{name: 'stalking', type:'przestępstwa'},
	{name: 'nielegalny handel', type:'przestępstwa'},
	// {name: 'pedofilia', type:'przestępstwa'},
	// {name: 'gwałt', type:'przestępstwa'},
	{name: 'wyłudzenie', type:'przestępstwa'},
	{name: 'porwanie', type:'przestępstwa'},
	{name: 'napad', type:'przestępstwa'},
	{name: 'spowodowanie wypadku', type:'przestępstwa'},
	{name: 'rabunek', type:'przestępstwa'},
	{name: 'włamanie', type:'przestępstwa'},
	{name: 'szantaż', type:'przestępstwa'},
	{name: 'zastraszanie', type:'przestępstwa'},
	{name: 'kradzież', type:'przestępstwa'},
	{name: 'pobicie', type:'przestępstwa'},
	{name: 'wandalizm', type:'przestępstwa'},
	{name: 'tortury', type:'przestępstwa'},
	{name: 'hackowanie', type:'przestępstwa'},
	{name: 'prześladowanie', type:'przestępstwa'},
	{name: 'cyber-bullying', type:'przestępstwa'},
	{name: 'infiltracja', type:'przestępstwa'},
	{name: 'porzucenie', type:'przestępstwa'},
	{name: 'oszczerstwo', type:'przestępstwa'},
	{name: 'korupcja', type:'przestępstwa'},
	{name: 'przywłaszczenie mienia', type:'przestępstwa'},
	{name: 'fałszerstwo', type:'przestępstwa'},
	{name: 'rozpijanie małoletniego', type:'przestępstwa'},
	
	// {name: 'halloween', type:'tradycje'},
	// {name: 'boże narodzenie', type:'tradycje'},
	// {name: 'wielkanoc', type:'tradycje'},
	// {name: 'boże ciało', type:'tradycje'},

	
	{name:`Among Us`, type: 'gry'},
	{name:`Rainbow Six`, type: 'gry'},
	{name:`Binding Of Isaac`, type: 'gry'},
	{name:`Shadow Of The Collosus`, type: 'gry'},
	{name:`Hitman`, type: 'gry'},
	{name:`Undertale`, type: 'gry'},
	{name:`GTA`, type: 'gry'},
	{name:`Fortnite`, type: 'gry'},
	{name:`Minecraft`, type: 'gry'},
	{name:`PubG`, type: 'gry'},
	{name:`League Of Legends`, type: 'gry'},
	{name:`Dota 2`, type: 'gry'},
	{name:`Heroes 3`, type: 'gry'},

	{name:`The Elder Scrolls`, type: 'gry'},
	{name:`Gothic`, type: 'gry'},
	{name:`Diablo`, type: 'gry'},
	{name:`Fallout 2`, type: 'gry'},
	{name:`baldur's gate`, type: 'gry'},
	{name:`Starcraft`, type: 'gry'},
	{name:`Sims`, type: 'gry'},
	{name:`Titan Quest`, type: 'gry'},
	{name:`Pillars Of Eternity`, type: 'gry'},
	{name:`Icewind Dale`, type: 'gry'},
	{name:`Dungeon Siege`, type: 'gry'},
	{name:`Disco Elysium`, type: 'gry'},
	{name:`The Last Of Us`, type: 'gry'},

	{name:`Uncharted`, type: 'gry'},
	{name:`Resident Evil`, type: 'gry'},
	{name:`Heartstone`, type: 'gry'},
	{name:`Warcraft`, type: 'gry'},

	{name:`Age of empires`, type: 'gry'},
	{name:`Civilization`, type: 'gry'},

	{name:`Mortal Kombat`, type: 'gry'},
	{name:`Street fighter`, type: 'gry'},
	{name:`Dead or alive`, type: 'gry'},
	{name:`Tekken`, type: 'gry'},
	{name:`Soul calibur`, type: 'gry'},
	{name:`smash bros`, type: 'gry'},

	{name:`Farming Simulator`, type: 'gry'},
	{name:`Euro Track Simulator Simulator`, type: 'gry'},

	{name:`Wow`, type: 'gry'},
	{name:`Overwatch`, type: 'gry'},
	{name:`Gears of war`, type: 'gry'},
	{name:`Warhammer 40k`, type: 'gry'},

	{name:`Lego games`, type: 'gry'},
	{name:`Plants vs zombies`, type: 'gry'},
	{name:`Geometry dash`, type: 'gry'},
	{name:`Roblox`, type: 'gry'},

	{name:`Wolfenstein 3d`, type: 'gry'},
	{name:`Battlefield`, type: 'gry'},
	{name:`Call Of Duty`, type: 'gry'},
	{name:`Doom`, type: 'gry'},
	{name:`Quake`, type: 'gry'},
	{name:`Duke Nukem`, type: 'gry'},
	{name:`Garrys Mod`, type: 'gry'},
	{name:`Half Life`, type: 'gry'},
	{name:`Unreal`, type: 'gry'},
	{name:`Borderlands`, type: 'gry'},

	{name:`Mario`, type: 'gry'},
	{name:`Pacman`, type: 'gry'},
	{name:`Tetris`, type: 'gry'},
	{name:`Megaman`, type: 'gry'},
	{name:`Worms`, type: 'gry'},
	{name:`Final fantasy`, type: 'gry'},
	{name:`Chrono trigger`, type: 'gry'},
	{name:`Contra`, type: 'gry'},

	{name:`x-com`, type: 'gry'},

	// {name:`Fifa`, type: 'gry'},
	// {name:`Pro evolution soccer`, type: 'gry'},
	// {name:`Footbal manager`, type: 'gry'},

	{name:`Dead by daylight`, type: 'gry'},
	{name:`Osu`, type: 'gry'},
	{name:`The escapist`, type: 'gry'},
	{name:`Ark survival`, type: 'gry'},
	{name:`BABA is You`, type: 'gry'},
	{name:`Terraria`, type: 'gry'},
	{name:`Ultimate Chicken Horse`, type: 'gry'},
	{name:`CS GO`, type: 'gry'},
	{name:`Red Dead Redemption`, type: 'gry'},
	{name:`Kingdom Come Deliverance`, type: 'gry'},
	{name:`Desperados`, type: 'gry'},
	{name:`Don't starve`, type: 'gry'},
	{name:`Mount and blade`, type: 'gry'},

	{name:`Forza Horizon`, type: 'gry'},
	{name:`Dirt`, type: 'gry'},
	{name:`Star wars racer`, type: 'gry'},
	{name:`Need for speed`, type: 'gry'},

	{name:`Mayday`, type: 'gry'},
	{name:`Dispel`, type: 'gry'},
	{name:`Dizzy`, type: 'gry'},
	{name:`Lemmings`, type: 'gry'},
	{name:`Descent`, type: 'gry'},
	{name:`Kknd`, type: 'gry'},
	{name:`Crusader`, type: 'gry'},
	{name:`Contructor`, type: 'gry'},
	{name:`Powerslide`, type: 'gry'},
	

	{ name: 'neker', type: 'potwory', source: 'witcher' },
	{ name: 'utopiec', type: 'potwory', source: 'witcher' },
	{ name: 'topielec', type: 'potwory', source: 'witcher,diablo' },
	{ name: 'leszy', type: 'potwory', source: 'witcher' },
	{ name: 'kikimora', type: 'potwory', source: 'witcher' },
	{ name: 'dremora', type: 'potwory', source: 'witcher' },
	{ name: 'skolopendromorf', type: 'potwory', source: 'witcher' },
	{ name: 'krabopająk', type: 'potwory', source: 'witcher' },
	{ name: 'katakan', type: 'potwory', source: 'witcher' },
	{ name: 'kłobuk', type: 'potwory', source: 'witcher' },
	{ name: 'gael', type: 'potwory', source: 'witcher' },
	{ name: 'kuroliszek', type: 'potwory', source: 'witcher', desc: 'chory bazyliszek' },
	{ name: 'wyjec', type: 'potwory', source: 'witcher' },
	{ name: 'żalnica', type: 'potwory', source: 'witcher' },
	{ name: 'skrzekacz', type: 'potwory', source: 'witcher' },
	{ name: 'endriaga', type: 'potwory', source: 'witcher' },
	{ name: 'erynia', type: 'potwory', source: 'witcher' },
	{ name: 'ekimma', type: 'potwory', source: 'witcher' },
	{ name: 'poroniec', type: 'potwory', source: 'witcher' },
	{ name: 'archespor', type: 'potwory', source: 'witcher' },
	{ name: 'mglak', type: 'potwory' },
	{ name: 'algul', type: 'potwory' },
	{ name: 'warg', type: 'potwory' },
	{ name: 'drown', type: 'potwory' },
	{ name: 'widłogon', type: 'potwory' },
	{ name: 'abishai', type: 'potwory' },

	{ name: 'yeti', type: 'potwory' },
	{ name: 'centaur', type: 'potwory' },
	{ name: 'wilkołak', type: 'potwory' },
	{ name: 'syrena', type: 'potwory' },
	{ name: 'minotaur', type: 'potwory' },
	{ name: 'meduza', type: 'potwory' },
	{ name: 'dżin', type: 'potwory' },
	{ name: 'czart', type: 'potwory' },
	{ name: 'driada', type: 'potwory' },
	{ name: 'zgnilec', type: 'potwory' },
	{ name: 'nazgul', type: 'potwory' },
	{ name: 'upiór', type: 'potwory' },
	{ name: 'bariaur', type: 'potwory' },
	{ name: 'skrzat', type: 'potwory' },
	{ name: 'skrzat', type: 'potwory' },
	{ name: 'bobołak', type: 'potwory' },
	{ name: 'draenei', type: 'potwory' },
	{ name: 'wendigo', type: 'potwory' },
	{ name: 'troll', type: 'potwory' },
	{ name: 'kobold', type: 'potwory' },
	{ name: 'gnoll', type: 'potwory' },
	{ name: 'goblin', type: 'potwory' },
	{ name: 'kościany', type: 'potwory' },
	{ name: 'smok', type: 'potwory' },
	{ name: 'chochlik', type: 'potwory' },
	{ name: 'hipogryf', type: 'potwory' },
	{ name: 'gryf', type: 'potwory' },
	{ name: 'harpia', type: 'potwory' },
	{ name: 'jednorożec', type: 'potwory' },
	{ name: 'ent', type: 'potwory' },
	{ name: 'drzewiec', type: 'potwory' },
	{ name: 'chimera', type: 'potwory' },
	{ name: 'beholder', type: 'potwory' },
	{ name: 'mantikora', type: 'potwory' },
	{ name: 'hydra', type: 'potwory' },
	{ name: 'rusałka', type: 'potwory' },
	{ name: 'nimfa', type: 'potwory' },
	{ name: 'duszek', type: 'potwory' },
	{ name: 'wróżka', type: 'potwory' },
	{ name: 'naga', type: 'potwory' },
	{ name: 'ogr', type: 'potwory' },
	{ name: 'tytan', type: 'potwory' },
	{ name: 'olbrzym', type: 'potwory' },
	{ name: 'jaszczuroczłek', type: 'potwory' },
	{ name: 'peryton', type: 'potwory' },
	{ name: 'szczuroczłek', type: 'potwory' },
	{ name: 'behemot', type: 'potwory' },
	{ name: 'cyklop', type: 'potwory' },
	{ name: 'feniks', type: 'potwory' },
	{ name: 'rok', type: 'potwory' },
	{ name: 'żmijoszpon', type: 'potwory' },
	{ name: 'ifryt', type: 'potwory' },
	{ name: 'cerber', type: 'potwory' },
	{ name: 'gorgon', type: 'potwory' },
	{ name: 'demogorgon', type: 'potwory' },
	{ name: 'gargulec', type: 'potwory' },
	{ name: 'pegaz', type: 'potwory' },
	{ name: 'wiwerna', type: 'potwory' },
	{ name: 'bazyliszek', type: 'potwory' },
	{ name: 'magiczny smok', type: 'potwory' },
	{ name: 'golem', type: 'potwory' },
	{ name: 'żywa zbroja', type: 'potwory' },
	{ name: 'ghul', type: 'potwory' },
	{ name: 'strzyga', type: 'potwory' },
	{ name: 'allip', type: 'potwory' },
	{ name: 'barghest', type: 'potwory' },
	{ name: 'czarny rycerz', type: 'potwory' },
	{ name: 'demilisz', type: 'potwory' },
	{ name: 'lisz', type: 'potwory' },
	{ name: 'wampir', type: 'potwory' },
	{ name: 'szkielet', type: 'potwory' },
	// { name: 'oślizg', type: 'potwory' },
	
	{ name: 'kot', tag: '', type: 'zwierzęta' },
	{ name: 'pies', tag: '', type: 'zwierzęta' },
	{ name: 'koń', tag: '', type: 'zwierzęta' },
	{ name: 'wilk', tag: '', type: 'zwierzęta' },
	{ name: 'krowa', tag: '', type: 'zwierzęta' },
	{ name: 'słoń', tag: '', type: 'zwierzęta' },
	{ name: 'owca', tag: '', type: 'zwierzęta' },
	{ name: 'małpa', tag: '', type: 'zwierzęta' },
	{ name: 'jeleń', tag: '', type: 'zwierzęta' },
	{ name: 'niedźwiedź', tag: '', type: 'zwierzęta' },
	{ name: 'żółw', tag: '', type: 'zwierzęta' },
	{ name: 'szympans', tag: '', type: 'zwierzęta' },
	{ name: 'lis', tag: '', type: 'zwierzęta' },
	{ name: 'koza', tag: '', type: 'zwierzęta' },
	{ name: 'goryl', tag: '', type: 'zwierzęta' },
	{ name: 'borsuk', tag: '', type: 'zwierzęta' },
	{ name: 'wiewiórka', tag: '', type: 'zwierzęta' },
	{ name: 'hiena', tag: '', type: 'zwierzęta' },
	{ name: 'jeż', tag: '', type: 'zwierzęta' },

	{ name: 'chomik', tag: '', type: 'zwierzęta' },
	{ name: 'mysz', tag: '', type: 'zwierzęta' },
	{ name: 'szczur', tag: '', type: 'zwierzęta' },
	{ name: 'zając', tag: '', type: 'zwierzęta' },
	{ name: 'królik', tag: '', type: 'zwierzęta' },

	{ name: 'skorpion', tag: '', type: 'zwierzęta' },
	{ name: 'kameleon', tag: '', type: 'zwierzęta' },
	{ name: 'jaszczurka', tag: '', type: 'zwierzęta' },

	{ name: 'pająk', tag: '', type: 'zwierzęta' },
	{ name: 'pancernik', tag: '', type: 'zwierzęta' },
	{ name: 'świnka morska', tag: '', type: 'zwierzęta' },
	{ name: 'surykatka', tag: '', type: 'zwierzęta' },
	{ name: 'bóbr', tag: '', type: 'zwierzęta' },
	{ name: 'kret', tag: '', type: 'zwierzęta' },
	{ name: 'wielbłąd', tag: '', type: 'zwierzęta' },
	{ name: 'osioł', tag: '', type: 'zwierzęta' },
	{ name: 'zebra', tag: '', type: 'zwierzęta' },
	{ name: 'łoś', tag: '', type: 'zwierzęta' },
	{ name: 'renifer', tag: '', type: 'zwierzęta' },
	{ name: 'dzik', tag: '', type: 'zwierzęta' },
	{ name: 'skunks', tag: '', type: 'zwierzęta' },
	{ name: 'świnia', tag: '', type: 'zwierzęta' },
	{ name: 'krokodyl', tag: '', type: 'zwierzęta' },
	{ name: 'ryś', tag: '', type: 'zwierzęta' },
	{ name: 'pantera', tag: '', type: 'zwierzęta' },
	{ name: 'tygrys', tag: '', type: 'zwierzęta' },
	{ name: 'lew', tag: '', type: 'zwierzęta' },
	{ name: 'wąż', tag: '', type: 'zwierzęta' },
	{ name: 'ropucha', tag: '', type: 'zwierzęta' },
	{ name: 'żaba', tag: '', type: 'zwierzęta' },
	{ name: 'lemur', tag: '', type: 'zwierzęta' },
	{ name: 'żubr', tag: '', type: 'zwierzęta' },
	{ name: 'żyrafa', tag: '', type: 'zwierzęta' },
	{ name: 'sarna', tag: '', type: 'zwierzęta' },
	{ name: 'koala', tag: '', type: 'zwierzęta' },
	{ name: 'panda', tag: '', type: 'zwierzęta' },
	{ name: 'rezus', tag: '', type: 'zwierzęta' },
	{ name: 'pawian', tag: '', type: 'zwierzęta' },
	{ name: 'palczak', tag: '', type: 'zwierzęta' },
	
	{ name: 'antylopa', tag: '', type: 'zwierzęta' },
	{ name: 'mewa', tag: '', type: 'zwierzęta' },
	{ name: 'biedronka', tag: '', type: 'zwierzęta' },
	{ name: 'żuk', tag: '', type: 'zwierzęta' },
	{ name: 'delfin', tag: '', type: 'zwierzęta' },
	{ name: 'dinozaur', tag: '', type: 'zwierzęta' },
	{ name: 'dzięcioł ', tag: '', type: 'zwierzęta' },
	{ name: 'dzik ', tag: '', type: 'zwierzęta' },
	{ name: 'wydra', tag: '', type: 'zwierzęta' },
	{ name: 'łasica', tag: '', type: 'zwierzęta' },
	{ name: 'flądra', tag: '', type: 'zwierzęta' },
	{ name: 'flaming', tag: '', type: 'zwierzęta' },
	{ name: 'pelikan', tag: '', type: 'zwierzęta' },
	{ name: 'gołąb', tag: '', type: 'zwierzęta' },
	{ name: 'gęś', tag: '', type: 'zwierzęta' },
	{ name: 'hipopotam', tag: '', type: 'zwierzęta' },
	{ name: 'indyk', tag: '', type: 'zwierzęta' },
	{ name: 'jaskółka', tag: '', type: 'zwierzęta' },
	{ name: 'jamnik', tag: '', type: 'zwierzęta' },
	{ name: 'kogut', tag: '', type: 'zwierzęta' },
	{ name: 'kura', tag: '', type: 'zwierzęta' },
	{ name: 'lama', tag: '', type: 'zwierzęta' },
	{ name: 'modliszka', tag: '', type: 'zwierzęta' },
	{ name: 'mamut', tag: '', type: 'zwierzęta' },
	{ name: 'mrówka', tag: '', type: 'zwierzęta' },
	{ name: 'nietoperz', tag: '', type: 'zwierzęta' },
	{ name: 'orka', tag: '', type: 'zwierzęta' },
	{ name: 'osa', tag: '', type: 'zwierzęta' },
	{ name: 'rekin', tag: '', type: 'zwierzęta' },
	{ name: 'rak', tag: '', type: 'zwierzęta' },
	{ name: 'struś', tag: '', type: 'zwierzęta' },
]

