
export default [

	{ name : '🤼‍♂ Submajter', ext: '', list: [''], desc: '', type: 'klasy postaci'},
	{ name : '✏ Drawer', ext: '', list: [''], desc: '', type: 'klasy postaci'},
	{ name : '📖 Writer',  ext: '', list: [''], desc: '', type: 'klasy postaci'},
	{ name : '📋 Presenter',  ext: '', list: [''], desc: '', type: 'klasy postaci'},
	{ name : '💬 Talker',  ext: '', list: [''], desc: '', type: 'klasy postaci'},
	{ name : '🎭 Improvisator',  ext: '', list: [''], desc: '', type: 'klasy postaci'},
	{ name : '📷 Cameraman', ext: '', list: [''], desc: '', type: 'klasy postaci'},
	{ name : '🔈 Englishspeaker', ext: '', list: [''], desc: '', type: 'klasy postaci'},
	{ name : '🎵 Musician', ext: '', list: [''], desc: '', type: 'klasy postaci'},
	
	{
		name : '🤼‍♂️Submajter',
		'tier 1 (list)' : ['Guard', 'Mount', 'Kimura lub Americana', 'Armbar', 'Guillotine Choke lub Rear Naked Choke'],
		'tier 2 (list)' : ['Side Mount', 'Wszystkie techniki z Tier I', 'Triangle Choke', 'Toehold'],
		'tier 3 (list)' : ['Heel Hook', 'Kneebar', 'Achilles', 'Praktyczne użycie technik w sparingach'],
		'tier 4 (list)' : ['Ucz innych jak bezpiecznie zakładać techniki (kontuzje ney ney)'],
		'tier 5 (list)' : ['W walce przechodź gardę i bądź w stanie zakładać poprawne techniki bez kontuzjowania siebie i przeciwnika'],
		type: 'achievement',
	},
	{
		name : '✏️Drawer',
		'tier 1 (list)' : ['Okiełznaj swoją kreskę, zwalcz sianowanie', 'Opanuj rysowanie prostych brył', 'Narysuj kilka ładnych/ciekawych kompozycji', 'Poświęć na jedną pracę 3x więcej czasu niż normalnie'],
		'tier 2 (list)' : ['Naucz się rysować gesture', 'Naucz się rysować różne tekstury (np. futro, metal, kamień, drewno)', 'Naucz się zasad działania perspektywy'],
		'tier 3 (list)' : ['Naucz się poprawnych proporcji postaci i twarzy', 'Wykonstruuj z prostych brył znajomy kształt'],
		'tier 4 (list)' : ['Ucz innych podstaw rysunku (zrób zajęcia lub pomagaj indywidualnie)'],
		'tier 5 (list)' : ['Stań się mistrzem w rysowaniu czegoś spoza twojej strefy komfortu'],
		type: 'achievement',
	},
	{
		name : '📖Writer',
		'tier 1 (list)' : ['Napisz opowiadanie podczas turnusu'],
		'tier 2 (list)' : ['Napisz opowiadanie razem z kimś, nauczcie się wypracowywać kompromisy tam gdzie wasze pomysły się nie zgadzają. Wykorzystajcie silne strony każdego z was by stworzyć jak najlepszą lekturę'],
		'tier 3 (list)' : ['Napisz opowiadanie, przeczytaj je na głos grupie, przyjmij każdą krytykę i spróbuj przepisać je uwzględniając wszystkie uwagi'],
		'tier 4 (list)' : ['Dawaj innym feedback i wskazówki jak mogą poprawić swoje pisanie / zorganizuj zajęcia z pisania'],
		'tier 5 (list)' : ['Pisz dużo i czytaj dużo. Rozwijaj swój styl i nie bój się eksperymentowania. Czerp co dobre z krytyki i uwag by stale podnosić swoje umiejętności'],
		type: 'achievement',
	},
	{
		name : '📋Presenter',
		'tier 1 (list)' : ['Wystąp z prezentacją przynajmniej 3 razy w ciągu turnusu'],
		'tier 2 (list)' : ['Przygotuj i przedstaw interaktywną prezentację z przykładami i interakcją widowni'],
		'tier 3 (list)' : ['Poprowadź aktywność "prezentacje" dla grupy'],
		'tier 4 (list)' : ['Pomóż komuś przygotować prezentację / zachęć kogoś do prezentacji'],
		'tier 5 (list)' : ['Nie wiem ziom TED talk czy coś...'],
		type: 'achievement',
	},
	{
		name: '💻Programmer',
		'tier 1 (list)' : ['Opanuj podstawy programowania (zmienne, funkcje, ify, pętle i obiekty)'],
		'tier 2 (list)' : ['Napisz funkcję która posortuje słowa w tekście od najkrótszego do najdłuższego.'],
		'tier 3 (list)' : ['Stwórz interaktywną stronkę / apkę / grę'],
		'tier 4 (list)' : ['Naucz kogoś podstaw programowania / Wytłumacz komuś koncept z którym ma problem'],
		'tier 5 (list)' : ['Hackermaning'],
		type: 'achievement',
	},
	{
		name : '💬Talker',
		'tier 1 (list)' : ['Uczestnicz aktywnie w rozmowach'],
		'tier 2 (list)' : ['Regularnie proponuj tematy do poruszenia na rozmowach'],
		'tier 3 (list)' : ['Poprowadź większą rozmowę z grupą'],
		'tier 4 (list)' : ['Przekonaj kogoś by poruszył w rozmowie ważny dla niego/niej temat'],
		'tier 5 (list)' : ['Rozmawiaj z ludźmi, bądź dobrym słuchaczem, poruszaj trudniejsze tematy jednak rób to z wyczuciem'],
		type: 'achievement',
	},
	{
		name : '🎭Improvisator',
		'tier 1 (list)' : ['Uczestnicz w przynajmniej jednej scence na każdej improwizacji'],
		'tier 2 (list)' : ['Znaj zasady improwizacji i staraj się do nich stosować'],
		'tier 3 (list)' : ['Poprowadź improwizację dla grupy'],
		'tier 4 (list)' : ['Ucz ludzi zasad improwizacji w praktyce, grzecznie zwracaj im na to uwagę i zachęcaj do próbowania jeszcze raz tym razem ich przestrzegając'],
		'tier 5 (list)' : ['Nie wiem, musisz improwizować...'],
		type: 'achievement',
	},
	{
		name : '📷Cameraman',
		'tier 1 (list)' : ['Opanuj obsługę aparatu', 'Chwyć za aparat i udokumentuj jakieś wydarzenie z warsztatów'],
		'tier 2 (list)' : ['Naucz się zasad dobrej kompozycji', 'Zrób serię powiązanych tematycznie zdjęć'],
		'tier 3 (list)' : ['Skłoń ludzi do grupowej sesji foto którą poprowadzisz'],
		'tier 4 (list)' : ['Ucz ludzi obsługi aparatu'],
		'tier 5 (list)' : ['Nagraj kompletny film podczas trunusu warsztatów'],
		type: 'achievement',
	},
	{
		name : '🔈Englishspeaker',
		'tier 1 (list)' : ['Aktywnie uczestnicz w rozmowach po angielsku'],
		'tier 2 (list)' : ['Czasami rozmawiaj z ludźmi po angielsku na codzień'],
		'tier 3 (list)' : ['Spontanicznie odpal grupie rozmowę po angielsku'],
		'tier 4 (list)' : ['Ucz innych angielskiego poprzez rozmowę nie tylko podczas zajęć'],
		'tier 5 (list)' : ['Tłumacz dobre materiały edukacyjne z angielskiego na polski i dziel się nimi z innymi'],
		type: 'achievement',
	},
	{
		name : '🎵Musician',
		'tier 1 (list)' : ['Naucz się 2~3 wybranych przez siebie skal tak by móc je zagrać obiema rękami'],
		'tier 2 (list)' : ['Wystąp na koncercie z jakimś utworkiem lub improwizacją.'],
		'tier 3 (list)' : [''],
		'tier 4 (list)' : ['Ucz innych ludzi skal itp'],
		'tier 5 (list)' : ['Nie wiem zapytaj Shnabubulę, pewnie zrobić OCRemix czy coś'],
		type: 'achievement',
},
	
]