export default [
  
  { name: 'kot', tag: '', type: 'zwierzęta' },
  { name: 'pies', tag: '', type: 'zwierzęta' },
  { name: 'koń', tag: '', type: 'zwierzęta' },
  { name: 'wilk', tag: '', type: 'zwierzęta' },
  { name: 'krowa', tag: '', type: 'zwierzęta' },
  { name: 'słoń', tag: '', type: 'zwierzęta' },
  { name: 'owca', tag: '', type: 'zwierzęta' },
  { name: 'małpa', tag: '', type: 'zwierzęta' },
  { name: 'jeleń', tag: '', type: 'zwierzęta' },
  { name: 'niedźwiedź', tag: '', type: 'zwierzęta' },
  { name: 'żółw', tag: '', type: 'zwierzęta' },
  { name: 'szympans', tag: '', type: 'zwierzęta' },
  { name: 'lis', tag: '', type: 'zwierzęta' },
  { name: 'koza', tag: '', type: 'zwierzęta' },
  { name: 'goryl', tag: '', type: 'zwierzęta' },
  { name: 'łasica', tag: '', type: 'zwierzęta' },
  { name: 'borsuk', tag: '', type: 'zwierzęta' },
  { name: 'wiewiórka', tag: '', type: 'zwierzęta' },
  { name: 'hiena', tag: '', type: 'zwierzęta' },
  
  { name: 'chomik', tag: '', type: 'zwierzęta' },
  { name: 'mysz', tag: '', type: 'zwierzęta' },
  { name: 'szczur', tag: '', type: 'zwierzęta' },
  { name: 'zając', tag: '', type: 'zwierzęta' },
  { name: 'królik', tag: '', type: 'zwierzęta' },
  
  { name: 'skorpion', tag: '', type: 'zwierzęta' },
  { name: 'kameleon', tag: '', type: 'zwierzęta' },
  { name: 'gekon', tag: '', type: 'zwierzęta' },
  { name: 'jaszczurka', tag: '', type: 'zwierzęta' },
  
  { name: 'pająk', tag: '', type: 'zwierzęta' },
  { name: 'pancernik', tag: '', type: 'zwierzęta' },
  { name: 'świnka morska', tag: '', type: 'zwierzęta' },
  { name: 'jeż', tag: '', type: 'zwierzęta' },
  { name: 'surykatka', tag: '', type: 'zwierzęta' },
  { name: 'bóbr', tag: '', type: 'zwierzęta' },
  { name: 'kret', tag: '', type: 'zwierzęta' },
  { name: 'wielbłąd', tag: '', type: 'zwierzęta' },
  { name: 'osioł', tag: '', type: 'zwierzęta' },
  { name: 'zebra', tag: '', type: 'zwierzęta' },
  { name: 'łoś', tag: '', type: 'zwierzęta' },
  { name: 'renifer', tag: '', type: 'zwierzęta' },
  { name: 'dzik', tag: '', type: 'zwierzęta' },
  { name: 'skunks', tag: '', type: 'zwierzęta' },
  { name: 'świnia', tag: '', type: 'zwierzęta' },
  { name: 'aligator', tag: '', type: 'zwierzęta' },
  { name: 'krokodyl', tag: '', type: 'zwierzęta' },
  { name: 'ryś', tag: '', type: 'zwierzęta' },
  { name: 'puma', tag: '', type: 'zwierzęta' },
  { name: 'pantera', tag: '', type: 'zwierzęta' },
  { name: 'jaguar', tag: '', type: 'zwierzęta' },
  { name: 'gepard', tag: '', type: 'zwierzęta' },
  { name: 'lampart', tag: '', type: 'zwierzęta' },
  { name: 'tygrys', tag: '', type: 'zwierzęta' },
  { name: 'lew', tag: '', type: 'zwierzęta' },
  { name: 'wąż', tag: '', type: 'zwierzęta' },
  { name: 'ropucha', tag: '', type: 'zwierzęta' },
  { name: 'żaba', tag: '', type: 'zwierzęta' },
  { name: 'lemur', tag: '', type: 'zwierzęta' },
  { name: 'bawół', tag: '', type: 'zwierzęta' },
  { name: 'bizon', tag: '', type: 'zwierzęta' },
  { name: 'żubr', tag: '', type: 'zwierzęta' },
  { name: 'sarna', tag: '', type: 'zwierzęta' },
  { name: 'żyrafa', tag: '', type: 'zwierzęta' },
  { name: 'koala', tag: '', type: 'zwierzęta' },
  { name: 'panda', tag: '', type: 'zwierzęta' },
  { name: 'rezus', tag: '', type: 'zwierzęta' },
  { name: 'pawian', tag: '', type: 'zwierzęta' },
  
  { name: 'ara', tag: '', type: 'zwierzęta' },
  { name: 'antylopa', tag: '', type: 'zwierzęta' },
  { name: 'albatros', tag: '', type: 'zwierzęta' },
  { name: 'anakonda', tag: '', type: 'zwierzęta' },
  { name: 'alpaka', tag: '', type: 'zwierzęta' },
  { name: 'arui', tag: '', type: 'zwierzęta' },
  { name: 'biedronka', tag: '', type: 'zwierzęta' },
  { name: 'bażant', tag: '', type: 'zwierzęta' },
  { name: 'czapla', tag: '', type: 'zwierzęta' },
  { name: 'chrabąszcz', tag: '', type: 'zwierzęta' },
  { name: 'cielak', tag: '', type: 'zwierzęta' },
  { name: 'cap', tag: '', type: 'zwierzęta' },
  { name: 'czajka', tag: '', type: 'zwierzęta' },
  { name: 'delfin', tag: '', type: 'zwierzęta' },
  { name: 'dinozaur', tag: '', type: 'zwierzęta' },
  { name: 'daniel', tag: '', type: 'zwierzęta' },
  { name: 'dzięcioł ', tag: '', type: 'zwierzęta' },
  { name: 'drozd ', tag: '', type: 'zwierzęta' },
  { name: 'dorsz ', tag: '', type: 'zwierzęta' },
  { name: 'dzik ', tag: '', type: 'zwierzęta' },
  { name: 'dudek', tag: '', type: 'zwierzęta' },
  { name: 'emu ', tag: '', type: 'zwierzęta' },
  { name: 'empala ', tag: '', type: 'zwierzęta' },
  { name: 'eland', tag: '', type: 'zwierzęta' },
  { name: 'elanus', tag: '', type: 'zwierzęta' },
  { name: 'emberiza', tag: '', type: 'zwierzęta' },
  { name: 'eremopila', tag: '', type: 'zwierzęta' },
  { name: 'fenek', tag: '', type: 'zwierzęta' },
  { name: 'foksterier ', tag: '', type: 'zwierzęta' },
  { name: 'fretka', tag: '', type: 'zwierzęta' },
  { name: 'flądra', tag: '', type: 'zwierzęta' },
  { name: 'flaming', tag: '', type: 'zwierzęta' },
  { name: 'gołąb', tag: '', type: 'zwierzęta' },
  { name: 'gęś', tag: '', type: 'zwierzęta' },
  { name: 'gawron', tag: '', type: 'zwierzęta' },
  { name: 'halibuty', tag: '', type: 'zwierzęta' },
  { name: 'hieny', tag: '', type: 'zwierzęta' },
  { name: 'hipopotamy', tag: '', type: 'zwierzęta' },
  { name: 'indyk', tag: '', type: 'zwierzęta' },
  { name: 'iguana', tag: '', type: 'zwierzęta' },
  { name: 'jastrząb', tag: '', type: 'zwierzęta' },
  { name: 'jak', tag: '', type: 'zwierzęta' },
  { name: 'jaskółka', tag: '', type: 'zwierzęta' },
  { name: 'jamnik', tag: '', type: 'zwierzęta' },
  { name: 'kogut', tag: '', type: 'zwierzęta' },
  { name: 'kura', tag: '', type: 'zwierzęta' },
  { name: 'lama', tag: '', type: 'zwierzęta' },
  { name: 'modliszka', tag: '', type: 'zwierzęta' },
  { name: 'muł', tag: '', type: 'zwierzęta' },
  { name: 'mamut', tag: '', type: 'zwierzęta' },
  { name: 'mrówka', tag: '', type: 'zwierzęta' },
  { name: 'norka', tag: '', type: 'zwierzęta' },
  { name: 'nietoperz', tag: '', type: 'zwierzęta' },
  { name: 'orka', tag: '', type: 'zwierzęta' },
  { name: 'osa', tag: '', type: 'zwierzęta' },
  { name: 'okoń', tag: '', type: 'zwierzęta' },
  { name: 'padalec', tag: '', type: 'zwierzęta' },
  { name: 'paź', tag: '', type: 'zwierzęta' },
  { name: 'pelikan', tag: '', type: 'zwierzęta' },
  { name: 'rekin', tag: '', type: 'zwierzęta' },
  { name: 'rak', tag: '', type: 'zwierzęta' },
  { name: 'rybitwa', tag: '', type: 'zwierzęta' },
  { name: 'struś', tag: '', type: 'zwierzęta' },
  { name: 'słowik', tag: '', type: 'zwierzęta' },
  { name: 'tarantula', tag: '', type: 'zwierzęta' },
  { name: 'tęcznik', tag: '', type: 'zwierzęta' },
  { name: 'uszatek', tag: '', type: 'zwierzęta' },
  { name: 'wydra', tag: '', type: 'zwierzęta' },
  { name: 'zaskroniec', tag: '', type: 'zwierzęta' },
  
  // MINERAŁY
  { name: 'Siarka rodzima', type: 'minerały' },
  { name: 'Szafir', type: 'minerały' },
  { name: 'Rubin', type: 'minerały' },
  { name: 'Piryt', type: 'minerały' },
  { name: 'Opal', type: 'minerały' },
  { name: 'Onyks', type: 'minerały' },
  { name: 'Molibdenit', type: 'minerały' },
  { name: 'Magnetyt', type: 'minerały' },
  { name: 'Lazuryt', type: 'minerały' },
  { name: 'Kryształ górski - kwarc', type: 'minerały' },
  { name: 'Korund', type: 'minerały' },
  { name: 'Hematyt', type: 'minerały' },
  { name: 'Halit - sól kamienna', type: 'minerały' },
  { name: 'Fluoryt', type: 'minerały' },
  { name: 'Diament', type: 'minerały' },
  { name: 'Bursztyn', type: 'minerały' },
  { name: 'Ametyst', type: 'minerały' },
  { name: 'Agat', type: 'minerały' },

  // JEDZENIE
  { name: 'kromka', type: 'jedzenie' },
  { name: 'bochen', type: 'jedzenie' },
  { name: 'wieprzowina', type: 'jedzenie' },
  { name: 'dziczyzna', type: 'jedzenie' },
  { name: 'jagnięcina', type: 'jedzenie' },
  { name: 'baranina', type: 'jedzenie' },
  { name: 'szynka', type: 'jedzenie' },
  { name: 'salami', type: 'jedzenie' },
  { name: 'sarnina', type: 'jedzenie' },
  { name: 'konina', type: 'jedzenie' },
  { name: 'wołowina', type: 'jedzenie' },
  { name: 'kawał mięsa', type: 'jedzenie' },
  { name: 'wędlina', type: 'jedzenie' },
  { name: 'makaron', type: 'jedzenie' },
  { name: 'żyto', type: 'jedzenie' },
  { name: 'proso', type: 'jedzenie' },
  { name: 'owies', type: 'jedzenie' },
  { name: 'pszenica', type: 'jedzenie' },
  { name: 'ziarno', type: 'jedzenie' },
  { name: 'bułka', type: 'jedzenie' },
  { name: 'chleb', type: 'jedzenie' },
  { name: 'pieczywo', type: 'jedzenie' },
  { name: 'mięso', type: 'jedzenie' },

  // UBRANIE
  { name: 'spodnie', type: 'ubranie' },
  { name: 'podkoszulka', type: 'ubranie' },
  { name: 'futro', type: 'ubranie' },
  { name: 'legginsy', type: 'ubranie' },
  { name: 'dżinsy', type: 'ubranie' },
  { name: 'spódnica', type: 'ubranie' },
  { name: 'sukienka', type: 'ubranie' },
  { name: 'płaszcz', type: 'ubranie' },
  { name: 'bluza', type: 'ubranie' },
  { name: 'skóry', type: 'ubranie' },
  { name: 'marynarka', type: 'ubranie' },
  { name: 'gorset', type: 'ubranie' },
  { name: 'kamizelka', type: 'ubranie' },
  { name: 'kurtka', type: 'ubranie' },
  { name: 'rękawy', type: 'ubranie' },
  { name: 'chusty', type: 'ubranie' },
  { name: 'łańcuchy', type: 'ubranie' },
  { name: 'rękawice', type: 'ubranie' },
  { name: 'mundur', type: 'ubranie' },
  { name: 'piżama', type: 'ubranie' },
  { name: 'odzież ochronna', type: 'ubranie' },
  { name: 'uniform', type: 'ubranie' },
  { name: 'szata', type: 'ubranie' },
  { name: 'koszula szpitalna', type: 'ubranie' },
  { name: 'garnitur', type: 'ubranie' },
  { name: 'szlafrok', type: 'ubranie' },

  { name: 'kaptur', type: 'ubranie' },
  { name: 'przepaska', type: 'ubranie' },
  { name: 'kapelusz', type: 'ubranie' },
  { name: 'czapka', type: 'ubranie' },
  { name: 'opaska', type: 'ubranie' },
  { name: 'bandana', type: 'ubranie' },

  { name: 'chusta', type: 'ubranie' },
  { name: 'szelki', type: 'ubranie' },
  { name: 'sznur', type: 'ubranie' },
  { name: 'pas', type: 'ubranie' },
  { name: 'peleryna', type: 'ubranie' },
  { name: 'sznurki' },
  { name: 'bandaże' },

  // POTWORY

  // BRONIE
  { name: 'miecz', type: 'broń, brońBiała' },
  { name: 'poganiacz bydła', type: 'broń, brońBiała' },
  { name: 'scyzoryk', type: 'broń, brońBiała' },
  { name: 'nóż', type: 'broń, brońBiała' },
  { name: 'naręczne ostrze', type: 'broń, brońBiała' },
  { name: 'rękawica', type: 'broń, brońBiała' },
  { name: 'kastet', type: 'broń, brońBiała' },
  { name: 'długi miecz', type: 'broń, brońBiała' },
  { name: 'którki miecz', type: 'broń, brońBiała' },
  { name: 'katana', type: 'broń, brońBiała' },
  { name: 'sejmitar', type: 'broń, brońBiała' },
  { name: 'piła', type: 'broń, brońBiała' },
  { name: 'kosa', type: 'broń, brońBiała' },
  { name: 'pałka', type: 'broń, brońBiała' },
  { name: 'bagnet', type: 'broń, brońBiała' },
  { name: 'maczuga', type: 'broń, brońBiała' },
  { name: 'sztylet', type: 'broń, brońBiała' },
  { name: 'pika', type: 'broń, brońBiała' },
  { name: 'halabarda', type: 'broń, brońBiała' },
  { name: 'berdysz', type: 'broń, brońBiała' },
  { name: 'laska', type: 'broń, brońBiała' },
  { name: 'kij', type: 'broń, brońBiała' },
  { name: 'cep bojowy', type: 'broń, brońBiała' },
  { name: 'szpada', type: 'broń, brońBiała' },
  { name: 'rapier', type: 'broń, brońBiała' },
  { name: 'korbacz', type: 'broń, brońBiała' },
  { name: 'nadziak', type: 'broń, brońBiała' },
  { name: 'morgenstern', type: 'broń, brońBiała' },
  { name: 'buława', type: 'broń, brońBiała' },
  { name: 'młotek', type: 'broń, brońBiała' },
  { name: 'młot bojowy', type: 'broń, brońBiała' },
  { name: 'kilof', type: 'broń, brońBiała' },
  { name: 'ciupaga', type: 'broń, brońBiała' },
  { name: 'wekiera', type: 'broń, brońBiała' },
  { name: 'młot', type: 'broń, brońBiała' },
  { name: 'topór', type: 'broń, brońBiała' },
  { name: 'włócznia', type: 'broń, brońBiała' },
  { name: 'dzida', type: 'broń, brońBiała' },
  { name: 'oszczep', type: 'broń, brońBiała' },
  { name: 'kłoda', type: 'broń, brońBiała' },
  { name: 'kamień', type: 'broń, brońBiała' },
  { name: 'koktail mołotowa', type: 'broń, brońDystansowa' },
  { name: 'pojemnik zapalający', type: 'broń, brońDystansowa' },
  { name: 'granat', type: 'broń, brońDystansowa' },
  { name: 'tomahawk', type: 'broń, brońDystansowa' },
  { name: 'nóż do rzucania', type: 'broń, brońDystansowa' },
  { name: 'kunai', type: 'broń, brońDystansowa' },
  { name: 'shuriken', type: 'broń, brońDystansowa' },
  { name: 'włócznia', type: 'broń, brońDystansowa' },
  { name: 'dzida', type: 'broń, brońDystansowa' },
  { name: 'oszczep', type: 'broń, brońDystansowa' },
  { name: 'kamień', type: 'broń, brońDystansowa' },
  { name: 'muszkiet', type: 'broń, brońDystansowa' },
  { name: 'proca', type: 'broń, brońDystansowa' },
  { name: 'kusza', type: 'broń, brońDystansowa' },
  { name: 'łuk', type: 'broń, brońDystansowa' },
  { name: 'pistolet skałkowy', type: 'broń, brońDystansowa' },
  
  // OWOCE
  { name: 'cytryna', type: 'owoce' },
  { name: 'grejpfrut', type: 'owoce' },
  { name: 'morela', type: 'owoce' },
  { name: 'śliwka', type: 'owoce' },
  { name: 'gruszka', type: 'owoce' },
  { name: 'jabłko', type: 'owoce' },
  { name: 'pożeczki', type: 'owoce' },
  { name: 'mango', type: 'owoce' },
  { name: 'nektarynka', type: 'owoce' },
  { name: 'banan', type: 'owoce' },
  { name: 'winogrona', type: 'owoce' },
  { name: 'brzoskwinia', type: 'owoce' },
  { name: 'ananas', type: 'owoce' },
  { name: 'kiwi', type: 'owoce' },
  { name: 'mandarynka', type: 'owoce' },
  { name: 'pomarańcza', type: 'owoce' },
  { name: 'arbuz', type: 'owoce' },
  { name: 'poziomka', type: 'owoce' },
  { name: 'malina', type: 'owoce' },
  { name: 'truskawka', type: 'owoce' },
  { name: 'czereśnia', type: 'owoce' },
  { name: 'wiśnia', type: 'owoce' },

  // WARZYWA
  { name: 'marchew', type: 'warzywa' },
  { name: 'soja', type: 'warzywa' },
  { name: 'dynia', type: 'warzywa' },
  { name: 'kalarepa', type: 'warzywa' },
  { name: 'rzepa', type: 'warzywa' },
  { name: 'fasola', type: 'warzywa' },
  { name: 'brukselki', type: 'warzywa' },
  { name: 'kalafior', type: 'warzywa' },
  { name: 'brokuły', type: 'warzywa' },
  { name: 'por', type: 'warzywa' },
  { name: 'seler', type: 'warzywa' },
  { name: 'pomidor', type: 'warzywa' },
  { name: 'pietruszka', type: 'warzywa' },
  { name: 'ogórek', type: 'warzywa' },
  { name: 'rzodkiew', type: 'warzywa' },
  { name: 'buraki', type: 'warzywa' },
  { name: 'kapusta', type: 'warzywa' },
  { name: 'ziemniaki', type: 'warzywa' },
  { name: 'ryż', type: 'warzywa' },

  // KWIATY
  { name: 'hortensje', type: 'kwiaty' },
  { name: 'słonecznik', type: 'kwiaty' },
  { name: 'goździk', type: 'kwiaty' },
  { name: 'lilia', type: 'kwiaty' },
  { name: 'storczyk', type: 'kwiaty' },
  { name: 'storczyk', type: 'kwiaty' },
  { name: 'zawilec', type: 'kwiaty' },
  { name: 'stokrotka', type: 'kwiaty' },
  { name: 'tulipan', type: 'kwiaty' },
  { name: 'róża', type: 'kwiaty' },

  // DRZEWA
  { name: 'kalina', type: 'drzewa' },
  { name: 'jarząb szwedzki', type: 'drzewa' },
  { name: 'wiązy', type: 'drzewa' },
  { name: 'głogi', type: 'drzewa' },
  { name: 'olsza', type: 'drzewa' },
  { name: 'jawor', type: 'drzewa' },
  { name: 'jesion', type: 'drzewa' },
  { name: 'jodła', type: 'drzewa' },
  { name: 'grab', type: 'drzewa' },
  { name: 'bez', type: 'drzewa' },
  { name: 'robinia', type: 'drzewa' },
  { name: 'cis', type: 'drzewa' },
  { name: 'modrzew', type: 'drzewa' },
  { name: 'wierzby', type: 'drzewa' },
  { name: 'osika', type: 'drzewa' },
  { name: 'leszczyna', type: 'drzewa' },
  { name: 'jarząb', type: 'drzewa' },
  { name: 'kasztanowiec', type: 'drzewa' },
  { name: 'dąb', type: 'drzewa' },
  { name: 'świerk', type: 'drzewa' },
  { name: 'sosna', type: 'drzewa' },
  { name: 'buk', type: 'drzewa' },
  { name: 'brzoza', type: 'drzewa' },
  { name: 'klon', type: 'drzewa' },
  { name: 'bananowiec', type: 'drzewa' },
  { name: 'palma', type: 'drzewa' },
  { name: 'sekwoja', type: 'drzewa' },
  { name: 'baobab', type: 'drzewa' },
  { name: 'wiśnia', type: 'drzewa' },
  { name: 'jabłoń', type: 'drzewa' },
  { name: 'lipa', type: 'drzewa' },

  // GRZYBY
  { name: 'opieńka', type: 'grzyby' },
  { name: 'czubajka', type: 'grzyby' },
  { name: 'koźlarz', type: 'grzyby' },
  { name: 'lisówka', type: 'grzyby' },
  { name: 'pieczarka', type: 'grzyby' },
  { name: 'borowik', type: 'grzyby' },
  { name: 'rydz', type: 'grzyby' },
  { name: 'surojadka', type: 'grzyby' },
  { name: 'wełnianka', type: 'grzyby' },
  { name: 'muchomor', type: 'grzyby' },
  { name: 'muchomor sromotnikowy', type: 'grzyby' },
  { name: 'kurka', type: 'grzyby' },
  { name: 'podgrzybek', type: 'grzyby' },
  { name: 'maślak', type: 'grzyby' },
  { name: 'prawdziwek', type: 'grzyby' },

  // PTAKI
  { name: 'kaczka', type: 'ptaki' },
  { name: 'paw', type: 'ptaki' },
  { name: 'łabędź', type: 'ptaki' },
  { name: 'struś', type: 'ptaki' },
  { name: 'pelikan', type: 'ptaki' },
  { name: 'flaming', type: 'ptaki' },
  { name: 'pingwin', type: 'ptaki' },
  { name: 'emu', type: 'ptaki' },
  { name: 'czapla', type: 'ptaki' },
  { name: 'bocian', type: 'ptaki' },
  { name: 'papuga', type: 'ptaki' },
  { name: 'sokół', type: 'ptaki' },
  { name: 'jaskółka', type: 'ptaki' },
  { name: 'wróbel', type: 'ptaki' },
  { name: 'koliber', type: 'ptaki' },
  { name: 'sójka', type: 'ptaki' },
  { name: 'sroka', type: 'ptaki' },
  { name: 'sowa', type: 'ptaki' },
  { name: 'gil', type: 'ptaki' },
  { name: 'wrona', type: 'ptaki' },
  { name: 'kruk', type: 'ptaki' },
  { name: 'orzeł', type: 'ptaki' },
  { name: 'jastrząb', type: 'ptaki' },
  { name: 'słowik', type: 'ptaki' },
  { name: 'gołąb', type: 'ptaki' },
  { name: 'indyk', type: 'ptaki' },
  { name: 'kiwi', type: 'ptaki' },
  { name: 'kogut', type: 'ptaki' },
  { name: 'kura', type: 'ptaki' },

  // OWADY
  { name: 'komar', type: 'owady' },
  { name: 'ważka', type: 'owady' },
  { name: 'trzmiel', type: 'owady' },
  { name: 'szerszeń', type: 'owady' },
  { name: 'osa', type: 'owady' },
  { name: 'pszczoła', type: 'owady' },
  { name: 'mrówka', type: 'owady' },
  { name: 'konik polny', type: 'owady' },
  { name: 'szarańcza', type: 'owady' },
  { name: 'modliszka', type: 'owady' },
  { name: 'glista', type: 'owady' },
  { name: 'robak', type: 'owady' },
  { name: 'motyl', type: 'owady' },
  { name: 'dżdżownica', type: 'owady' },
  { name: 'żuk', type: 'owady' },
  { name: 'karaluch', type: 'owady' },
  { name: 'pchła', type: 'owady' },
  { name: 'muszka', type: 'owady' },
  { name: 'mucha', type: 'owady' },

  // RYBY
  { name: 'koi', type: 'ryby' },
  { name: 'frotka', type: 'ryby' },
  { name: 'dorsz', type: 'ryby' },
  { name: 'okoń', type: 'ryby' },
  { name: 'karaś', type: 'ryby' },
  { name: 'lin', type: 'ryby' },
  { name: 'sandacz', type: 'ryby' },
  { name: 'leszcz', type: 'ryby' },
  { name: 'ukleja', type: 'ryby' },
  { name: 'sieja', type: 'ryby' },
  { name: 'płotka', type: 'ryby' },
  { name: 'tuńczyk', type: 'ryby' },
  { name: 'błazenek', type: 'ryby' },
  { name: 'węgorz', type: 'ryby' },
  { name: 'płetwal', type: 'ryby' },
  { name: 'wieloryb', type: 'ryby' },
  { name: 'makrela', type: 'ryby' },
  { name: 'łosoś', type: 'ryby' },
  { name: 'karp', type: 'ryby' },
  { name: 'rekin', type: 'ryby' },

  // WODNE
  { name: 'delfin', type: 'wodne' },
  { name: 'orka', type: 'wodne' },
  { name: 'konik morski', type: 'wodne' },
  { name: 'polip', type: 'wodne' },
  { name: 'meduza', type: 'wodne' },
  { name: 'rozgwiazda', type: 'wodne' },
  { name: 'płaszczka', type: 'wodne' },
  { name: 'mors', type: 'wodne' },
  { name: 'foka', type: 'wodne' },
  { name: 'krewetka', type: 'wodne' },
  { name: 'krab', type: 'wodne' },
  { name: 'rak', type: 'wodne' },

  // PANCERZE
  { name: 'skórzany pancerz ćwiekowany', type: 'pancerze' },
  { name: 'skórzany pancerz', type: 'pancerze' },
  // { name: 'peleryna', type: 'pancerze' },
  // { name: 'narzuta', type: 'pancerze' },
  { name: 'kirys', type: 'pancerze' },
  // { name: 'zbroja turniejowa', type: 'pancerze' },
  { name: 'ciężka zbroja płytowa', type: 'pancerze' },
  { name: 'zbroja płytowa', type: 'pancerze' },
  { name: 'lekka zbroja płytowa', type: 'pancerze' },
  { name: 'zbroja karacenowa', type: 'pancerze' },
  { name: 'kolczuga', type: 'pancerze' },
  { name: 'napierśnik', type: 'pancerze' },
  { name: 'zbroja łuskowa', type: 'pancerze' },
  { name: 'zbroja pierścieniowa', type: 'pancerze' },
  { name: 'ćwiekowana zbroja', type: 'pancerze' },
  { name: 'skórzana zbroja', type: 'pancerze' },
  { name: 'pikowana zbroja', type: 'pancerze' },
  { name: 'skórzana kurtka', type: 'pancerze' },
  { name: 'zbroja pełna', type: 'pancerze' },
  { name: 'zbroja samurajska', type: 'pancerze' },
  // { name: 'spodnie pierścieniowe', type: 'pancerze' },
  // { name: 'spodnie kolcze', type: 'pancerze' },
  { name: 'ćwiekowane spodnie', type: 'pancerze' },
  { name: 'korona', type: 'pancerze' },
  { name: 'hełm', type: 'pancerze' },
  { name: 'szyszak', type: 'pancerze' },
  { name: 'kaptur', type: 'pancerze' },
  { name: 'stalowe rękawice', type: 'pancerze' },
  { name: 'kolcze rękawice', type: 'pancerze' },
  { name: 'skórzane rękawice', type: 'pancerze' },
  { name: 'rękawice', type: 'pancerze' },
  { name: 'skórzane spodnie', type: 'pancerze' },
  { name: 'nagolenniki', type: 'pancerze' },


  // CZĘŚCI ARCHITEKTONICZNE WNĘTRZA
  { name: 'sufit'},
  { name: 'podłoga'},
  { name: 'ściana'},
  { name: 'schody'},
  { name: 'uchwyt'},
  
  { name: 'komin'},
  // WNĘTRZE POKOJU
  { name: 'obraz'},
  { name: 'dywan'},
  { name: 'okno'},
  { name: 'drzwi'},
  { name: 'kosz na śmieci'},
  { name: 'biurko'},
  { name: 'kredens'},
  { name: 'stół'},
  { name: 'krzesło'},
  { name: 'fotel'},
  { name: 'firanka'},
  { name: 'kanapa'},
  { name: 'lampa'},
  { name: 'żyrandol'},
  { name: 'lampion'},
  { name: 'półki'},
  { name: 'szafa'},
  { name: 'dodatkowe'},

  // KUCHNIA
  { name: 'blat'},
  { name: 'czajnik'},
  { name: 'garnek'},
  { name: 'miska'},
  { name: 'lodówka'},
  { name: 'kran'},
  { name: 'zlew'},
  { name: 'łyżka'},
  { name: 'nóż'},
  { name: 'widelec'},
]