
export default [

	{ name: 'rysunkowe państwa miasta', ext: '', desc: '', type: 'aktywność rysunkowa' },
	{ name: 'rysunek z zestawu elementów', ext: '', desc: '', type: 'aktywność rysunkowa' },
	{ name: 'rysujemy siebie', list: ['gesture', 'portret', 'dłonie'], ext: '', desc: '', type: 'aktywność rysunkowa' },
	{ name: 'rysunek z opisu', ext: '', desc: '', type: 'aktywność rysunkowa' },
	{ name: 'rysujemy przypadkowe obiekty z domu', ext: '', desc: '', type: 'aktywność rysunkowa' },
	{ name: 'rysunkowa zgadywanka', ext: 'kalambury', desc: 'Ktoś rysuje a pozostali zgadują co to będzie - raczej na kompie', type: 'aktywność rysunkowa' },
	{ name: 'rysunkowa zgadywanka', ext: 'na kartkach', desc: 'Każdy dostaje listę tematów do narysowania i 3 interwały, pierwszy 30s, drugi: 2min, trzeci 5min, po każdym pokazujemy sobie i próbujemy dopasować element z listy do rysunku', type: 'aktywność rysunkowa' },
	
	{ name: 'przerysowywanie concept artów z neta', ext: '', desc: '', type: 'aktywność rysunkowa' },
	{ name: 'zgadnij styl', ext: 'czyja to pracka', desc: '', type: 'aktywność rysunkowa' },
	{ name: 'object fusion', ext: '', list: ['lew i pralka', 'kot i chrabąszcz'], desc: 'Połączenie cech wielu obiektów, można korzystać z list', type: 'aktywność rysunkowa' },
	

	{ name: 'lotniskowiec', type: 'narysuj' },
	{ name: 'samolot', type: 'narysuj' },
	{ name: 'budzik', type: 'narysuj' },
	{ name: 'karetka', type: 'narysuj' },
	{ name: 'anioł', type: 'narysuj' },
	{ name: 'mrówka', type: 'narysuj' },
	{ name: 'kowadło', type: 'narysuj' },
	{ name: 'jabłko', type: 'narysuj' },
	{ name: 'ramię', type: 'narysuj' },
	{ name: 'szparag', type: 'narysuj' },
	{ name: 'topór', type: 'narysuj' },
	{ name: 'plecak', type: 'narysuj' },
	{ name: 'banan', type: 'narysuj' },
	{ name: 'bandaż', type: 'narysuj' },
	{ name: 'stodoła', type: 'narysuj' },
	{ name: 'baseball', type: 'narysuj' },
	{ name: `kij bejsbolowy`, type: 'narysuj' },
	{ name: 'kosz', type: 'narysuj' },
	{ name: 'koszykówka', type: 'narysuj' },
	{ name: 'nietoperz', type: 'narysuj' },
	{ name: 'wanna', type: 'narysuj' },
	{ name: 'plaża', type: 'narysuj' },
	{ name: 'niedźwiedź', type: 'narysuj' },
	{ name: 'zarost', type: 'narysuj' },
	{ name: 'łóżko', type: 'narysuj' },
	{ name: 'pszczoła', type: 'narysuj' },
	{ name: 'pas', type: 'narysuj' },
	{ name: 'ławka', type: 'narysuj' },
	{ name: 'rower', type: 'narysuj' },
	{ name: 'lornetka', type: 'narysuj' },
	{ name: 'ptak', type: 'narysuj' },
	{ name: 'tort urodzinowy', type: 'narysuj' },
	{ name: 'jeżyna', type: 'narysuj' },
	{ name: 'borówka amerykańska', type: 'narysuj' },
	{ name: 'książka', type: 'narysuj' },
	{ name: 'bumerang', type: 'narysuj' },
	{ name: 'nakrętka od butelki', type: 'narysuj' },
	{ name: 'mucha', type: 'narysuj' },
	{ name: 'bransoletka', type: 'narysuj' },
	{ name: 'mózg', type: 'narysuj' },
	{ name: 'chleb', type: 'narysuj' },
	{ name: 'most', type: 'narysuj' },
	{ name: 'brokuły', type: 'narysuj' },
	{ name: 'miotła', type: 'narysuj' },
	{ name: 'wiadro', type: 'narysuj' },
	{ name: 'spychacz', type: 'narysuj' },
	{ name: 'walec', type: 'narysuj' },
	{ name: 'walec (pojazd)', type: 'narysuj' },
	{ name: 'autobus', type: 'narysuj' },
	{ name: 'krzak', type: 'narysuj' },
	{ name: 'motyl', type: 'narysuj' },
	{ name: 'kaktus', type: 'narysuj' },
	{ name: 'ciasto', type: 'narysuj' },
	{ name: 'kalkulator', type: 'narysuj' },
	{ name: 'kalendarz', type: 'narysuj' },
	{ name: 'wielbłąd', type: 'narysuj' },
	{ name: 'aparat fotograficzny', type: 'narysuj' },
	{ name: 'kamuflaż', type: 'narysuj' },
	{ name: 'ognisko', type: 'narysuj' },
	{ name: 'świeca', type: 'narysuj' },
	{ name: 'armata', type: 'narysuj' },
	{ name: 'kajak', type: 'narysuj' },
	{ name: 'samochód', type: 'narysuj' },
	{ name: 'marchewka', type: 'narysuj' },
	{ name: 'zamek (budowla)', type: 'narysuj' },
	{ name: 'zamek (do drzwi)', type: 'narysuj' },
	{ name: 'zamek błyskawiczny', type: 'narysuj' },
	{ name: 'kot', type: 'narysuj' },
	{ name: 'wentylator sufitowy', type: 'narysuj' },
	{ name: 'wiolonczela', type: 'narysuj' },
	{ name: 'komórka', type: 'narysuj' },
	{ name: 'krzesło', type: 'narysuj' },
	{ name: 'fotel', type: 'narysuj' },
	{ name: 'żyrandol', type: 'narysuj' },
	{ name: 'kościół', type: 'narysuj' },
	{ name: 'okrąg', type: 'narysuj' },
	{ name: 'klarnet', type: 'narysuj' },
	{ name: 'zegar', type: 'narysuj' },
	{ name: 'chmura', type: 'narysuj' },
	{ name: 'filiżanka kawy', type: 'narysuj' },
	{ name: 'kompas', type: 'narysuj' },
	{ name: 'komputer', type: 'narysuj' },
	{ name: 'ciastko', type: 'narysuj' },
	{ name: 'chłodnica', type: 'narysuj' },
	{ name: 'sofa', type: 'narysuj' },
	{ name: 'krowa', type: 'narysuj' },
	{ name: 'krab', type: 'narysuj' },
	{ name: 'pastel', type: 'narysuj' },
	{ name: 'krokodyl', type: 'narysuj' },
	{ name: 'korona', type: 'narysuj' },
	{ name: 'statek wycieczkowy', type: 'narysuj' },
	{ name: 'puchar', type: 'narysuj' },
	{ name: 'diament', type: 'narysuj' },
	{ name: 'zmywarka', type: 'narysuj' },
	{ name: 'trampolina', type: 'narysuj' },
	{ name: 'pies', type: 'narysuj' },
	{ name: 'delfin', type: 'narysuj' },
	{ name: 'pączek', type: 'narysuj' },
	{ name: 'drzwi', type: 'narysuj' },
	{ name: 'smok', type: 'narysuj' },
	{ name: 'kredens', type: 'narysuj' },
	{ name: 'wiercić', type: 'narysuj' },
	{ name: 'bębny', type: 'narysuj' },
	{ name: 'kaczka', type: 'narysuj' },
	{ name: 'ucho', type: 'narysuj' },
	{ name: 'łokieć', type: 'narysuj' },
	{ name: 'słoń', type: 'narysuj' },
	{ name: 'koperta', type: 'narysuj' },
	{ name: 'gumka do ścierania', type: 'narysuj' },
	{ name: 'oko', type: 'narysuj' },
	{ name: 'okulary', type: 'narysuj' },
	{ name: 'twarz', type: 'narysuj' },
	{ name: 'wentylator', type: 'narysuj' },
	{ name: 'pióro', type: 'narysuj' },
	{ name: 'płot', type: 'narysuj' },
	{ name: 'palec', type: 'narysuj' },
	{ name: 'hydrant', type: 'narysuj' },
	{ name: 'kominek', type: 'narysuj' },
	{ name: 'wóz strażacki', type: 'narysuj' },
	{ name: 'ryba', type: 'narysuj' },
	{ name: 'flaming', type: 'narysuj' },
	{ name: 'latarka', type: 'narysuj' },
	{ name: 'japonki', type: 'narysuj' },
	{ name: 'lampa podłogowa', type: 'narysuj' },
	{ name: 'kwiat', type: 'narysuj' },
	{ name: 'latający spodek', type: 'narysuj' },
	{ name: 'stopa', type: 'narysuj' },
	{ name: 'widelec', type: 'narysuj' },
	{ name: 'żaba', type: 'narysuj' },
	{ name: 'patelnia', type: 'narysuj' },
	{ name: 'ogród', type: 'narysuj' },
	{ name: 'wąż ogrodowy', type: 'narysuj' },
	{ name: 'żyrafa', type: 'narysuj' },
	{ name: 'kozia bródka', type: 'narysuj' },
	{ name: 'kij golfowy', type: 'narysuj' },
	{ name: 'winogrona', type: 'narysuj' },
	{ name: 'trawa', type: 'narysuj' },
	{ name: 'gitara', type: 'narysuj' },
	{ name: 'hamburger', type: 'narysuj' },
	{ name: 'młotek', type: 'narysuj' },
	{ name: 'dłoń', type: 'narysuj' },
	{ name: 'harfa', type: 'narysuj' },
	{ name: 'kapelusz', type: 'narysuj' },
	{ name: 'słuchawki', type: 'narysuj' },
	{ name: 'jeż', type: 'narysuj' },
	{ name: 'śmigłowiec', type: 'narysuj' },
	{ name: 'kask', type: 'narysuj' },
	{ name: 'sześciokąt', type: 'narysuj' },
	{ name: 'krążek hokejowy', type: 'narysuj' },
	{ name: 'kij hokejowy', type: 'narysuj' },
	{ name: 'koń', type: 'narysuj' },
	{ name: 'szpital', type: 'narysuj' },
	{ name: 'balon na gorące powietrze', type: 'narysuj' },
	{ name: 'hot dog', type: 'narysuj' },
	{ name: 'jacuzzi', type: 'narysuj' },
	{ name: 'klepsydra', type: 'narysuj' },
	{ name: 'dom', type: 'narysuj' },
	{ name: 'roślina domowa', type: 'narysuj' },
	{ name: 'huragan', type: 'narysuj' },
	{ name: 'lody', type: 'narysuj' },
	{ name: 'kurtka', type: 'narysuj' },
	{ name: 'więzienie', type: 'narysuj' },
	{ name: 'kangur', type: 'narysuj' },
	{ name: 'klucz', type: 'narysuj' },
	{ name: 'klawiatura', type: 'narysuj' },
	{ name: 'kolano', type: 'narysuj' },
	{ name: 'nóż', type: 'narysuj' },
	{ name: 'drabina', type: 'narysuj' },
	{ name: 'latarnia', type: 'narysuj' },
	{ name: 'laptop', type: 'narysuj' },
	{ name: 'liść', type: 'narysuj' },
	{ name: 'noga', type: 'narysuj' },
	{ name: 'żarówka', type: 'narysuj' },
	{ name: 'zapalniczka', type: 'narysuj' },
	{ name: 'latarnia morska', type: 'narysuj' },
	{ name: 'błyskawica', type: 'narysuj' },
	{ name: 'linia', type: 'narysuj' },
	{ name: 'lew', type: 'narysuj' },
	{ name: 'pomadka', type: 'narysuj' },
	{ name: 'homar', type: 'narysuj' },
	{ name: 'lizak', type: 'narysuj' },
	{ name: 'skrzynka pocztowa', type: 'narysuj' },
	{ name: 'mapa', type: 'narysuj' },
	{ name: 'mecze', type: 'narysuj' },
	{ name: 'megafon', type: 'narysuj' },
	{ name: 'syrena', type: 'narysuj' },
	{ name: 'mikrofon', type: 'narysuj' },
	{ name: 'kuchenka mikrofalowa', type: 'narysuj' },
	{ name: 'małpa', type: 'narysuj' },
	{ name: 'księżyc', type: 'narysuj' },
	{ name: 'komar', type: 'narysuj' },
	{ name: 'motocykl', type: 'narysuj' },
	{ name: 'góra', type: 'narysuj' },
	{ name: 'mysz', type: 'narysuj' },
	{ name: 'wąsy', type: 'narysuj' },
	{ name: 'usta', type: 'narysuj' },
	{ name: 'kubek', type: 'narysuj' },
	{ name: 'grzyb', type: 'narysuj' },
	{ name: 'gwóźdź', type: 'narysuj' },
	{ name: 'naszyjnik', type: 'narysuj' },
	{ name: 'nos', type: 'narysuj' },
	{ name: 'ocean', type: 'narysuj' },
	{ name: 'ośmiokąt', type: 'narysuj' },
	{ name: 'ośmiornica', type: 'narysuj' },
	{ name: 'cebula', type: 'narysuj' },
	{ name: 'piekarnik', type: 'narysuj' },
	{ name: 'sowa', type: 'narysuj' },
	{ name: 'pędzel', type: 'narysuj' },
	{ name: 'puszka farby', type: 'narysuj' },
	{ name: 'drzewo palmowe', type: 'narysuj' },
	{ name: 'panda', type: 'narysuj' },
	{ name: 'spodnie', type: 'narysuj' },
	{ name: 'spinacz', type: 'narysuj' },
	{ name: 'spadochron', type: 'narysuj' },
	{ name: 'papuga', type: 'narysuj' },
	{ name: 'paszport', type: 'narysuj' },

	{ name: 'znacznik', type: 'narysuj' },

	{ name: 'gruszka', type: 'narysuj' },
	{ name: 'groszek', type: 'narysuj' },
	{ name: 'ołówek', type: 'narysuj' },
	{ name: 'pingwin', type: 'narysuj' },
	{ name: 'fortepian', type: 'narysuj' },
	{ name: 'pickup', type: 'narysuj' },
	{ name: 'obraz', type: 'narysuj' },
	{ name: 'ramka', type: 'narysuj' },
	{ name: 'świnia', type: 'narysuj' },
	{ name: 'poduszka', type: 'narysuj' },
	{ name: 'ananas', type: 'narysuj' },
	{ name: 'pizza', type: 'narysuj' },
	{ name: 'szczypce', type: 'narysuj' },
	{ name: 'radiowóz', type: 'narysuj' },
	{ name: 'staw', type: 'narysuj' },
	{ name: 'basen', type: 'narysuj' },
	{ name: 'lód na patyku', type: 'narysuj' },
	{ name: 'pocztówka', type: 'narysuj' },
	{ name: 'ziemniak', type: 'narysuj' },
	{ name: 'gniazdo zasilania', type: 'narysuj' },
	{ name: 'portmonetka', type: 'narysuj' },
	{ name: 'królik', type: 'narysuj' },
	{ name: 'szop pracz', type: 'narysuj' },
	{ name: 'radio', type: 'narysuj' },
	{ name: 'deszcz', type: 'narysuj' },
	{ name: 'tęcza', type: 'narysuj' },
	{ name: 'grabie', type: 'narysuj' },
	{ name: 'pilot zdalny', type: 'narysuj' },
	{ name: 'pilot (myśliwca)', type: 'narysuj' },
	{ name: 'nosorożec', type: 'narysuj' },
	{ name: 'karabin', type: 'narysuj' },
	{ name: 'miotacz ognia', type: 'narysuj' },
	{ name: 'rzeka', type: 'narysuj' },
	{ name: 'kolejka górska', type: 'narysuj' },
	{ name: 'rolki', type: 'narysuj' },
	{ name: 'żaglówka', type: 'narysuj' },
	{ name: 'kanapka', type: 'narysuj' },
	{ name: 'piła', type: 'narysuj' },
	{ name: 'saksofon', type: 'narysuj' },
	{ name: 'autobus szkolny', type: 'narysuj' },
	{ name: 'nożyce', type: 'narysuj' },
	{ name: 'skorpion', type: 'narysuj' },
	{ name: 'śrubokręt', type: 'narysuj' },
	{ name: 'żółw morski', type: 'narysuj' },

	{ name: 'rekin', type: 'narysuj' },
	{ name: 'owca', type: 'narysuj' },
	{ name: 'but', type: 'narysuj' },
	{ name: 'szorty', type: 'narysuj' },
	{ name: 'łopata', type: 'narysuj' },
	{ name: 'łopata do śniegu', type: 'narysuj' },
	{ name: 'tonąć', type: 'narysuj' },
	{ name: 'deskorolka', type: 'narysuj' },
	{ name: 'czaszka', type: 'narysuj' },
	{ name: 'drapacz chmur', type: 'narysuj' },
	{ name: 'śpiwór', type: 'narysuj' },
	{ name: 'uśmiechnięta twarz', type: 'narysuj' },
	{ name: 'ślimak', type: 'narysuj' },
	{ name: 'wąż', type: 'narysuj' },
	{ name: 'kobra (wąż)', type: 'narysuj' },
	{ name: 'rurka do nurkowania', type: 'narysuj' },
	{ name: 'płatek śniegu', type: 'narysuj' },
	{ name: 'bałwan', type: 'narysuj' },
	{ name: 'piłka nożna', type: 'narysuj' },
	{ name: 'skarpetka', type: 'narysuj' },
	{ name: 'motorówka', type: 'narysuj' },
	{ name: 'pająk', type: 'narysuj' },
	{ name: 'łyżka', type: 'narysuj' },
	{ name: 'arkusz', type: 'narysuj' },
	{ name: 'plac', type: 'narysuj' },
	{ name: 'kwadrat', type: 'narysuj' },
	{ name: 'zakrętas', type: 'narysuj' },
	{ name: 'wiewiórka', type: 'narysuj' },
	{ name: 'schody', type: 'narysuj' },
	{ name: 'gwiazda', type: 'narysuj' },
	{ name: 'stek', type: 'narysuj' },
	{ name: 'wieża stereo', type: 'narysuj' },
	{ name: 'stetoskop', type: 'narysuj' },
	{ name: 'szwy', type: 'narysuj' },
	{ name: 'znak stopu', type: 'narysuj' },
	{ name: 'kuchenka', type: 'narysuj' },
	{ name: 'truskawka', type: 'narysuj' },
	{ name: 'światła', type: 'narysuj' },
	{ name: 'fasolka szparagowa', type: 'narysuj' },
	{ name: 'łódź podwodna', type: 'narysuj' },
	{ name: 'walizka', type: 'narysuj' },
	{ name: 'słońce', type: 'narysuj' },
	{ name: 'łabędź', type: 'narysuj' },
	{ name: 'sweter', type: 'narysuj' },
	{ name: 'huśtawka', type: 'narysuj' },
	{ name: 'miecz', type: 'narysuj' },
	{ name: 'strzykawka', type: 'narysuj' },
	{ name: 'stół', type: 'narysuj' },
	{ name: 'czajniczek', type: 'narysuj' },
	{ name: 'miś', type: 'narysuj' },
	{ name: 'telefon', type: 'narysuj' },
	{ name: 'telewizja', type: 'narysuj' },
	{ name: 'rakietka tenisowa', type: 'narysuj' },
	{ name: 'namiot', type: 'narysuj' },
	{ name: 'Wieża Eiffla', type: 'narysuj' },
	{ name: 'Wielki Mur Chiński', type: 'narysuj' },
	{ name: 'Mona Lisa', type: 'narysuj' },
	{ name: 'tygrys', type: 'narysuj' },
	{ name: 'opiekacz', type: 'narysuj' },
	{ name: 'palec u nogi', type: 'narysuj' },
	{ name: 'toaleta', type: 'narysuj' },
	{ name: 'ząb', type: 'narysuj' },
	{ name: 'zęby', type: 'narysuj' },
	{ name: 'szczoteczka do zębów', type: 'narysuj' },
	{ name: 'pasta do zębów', type: 'narysuj' },
	{ name: 'tornado', type: 'narysuj' },
	{ name: 'ciągnik', type: 'narysuj' },
	{ name: 'sygnalizacja świetlna', type: 'narysuj' },
	{ name: 'pociąg', type: 'narysuj' },
	{ name: 'drzewo', type: 'narysuj' },
	{ name: 'trójkąt', type: 'narysuj' },
	{ name: 'puzon', type: 'narysuj' },
	{ name: 'trąbka', type: 'narysuj' },
	{ name: 'samochód ciężarowy', type: 'narysuj' },
	{ name: 'podkoszulek', type: 'narysuj' },
	{ name: 'parasol', type: 'narysuj' },
	{ name: 'bielizna', type: 'narysuj' },
	{ name: 'furgonetka', type: 'narysuj' },
	{ name: 'wazon', type: 'narysuj' },
	{ name: 'skrzypce', type: 'narysuj' },
	{ name: 'pralka', type: 'narysuj' },
	{ name: 'arbuz', type: 'narysuj' },
	{ name: 'zjeżdżalnia wodna', type: 'narysuj' },
	{ name: 'wieloryb', type: 'narysuj' },
	{ name: 'koło', type: 'narysuj' },
	{ name: 'wiatrak', type: 'narysuj' },
	{ name: 'butelka wina', type: 'narysuj' },
	{ name: 'lampka wina', type: 'narysuj' },
	{ name: 'zegarek na rękę', type: 'narysuj' },
	{ name: 'joga', type: 'narysuj' },
	{ name: 'zebra', type: 'narysuj' },
	{ name: 'telewizor', type: 'narysuj' },
	{ name: 'butelka', type: 'narysuj' },
	{ name: 'aparat', type: 'narysuj' },
	{ name: 'kieliszek', type: 'narysuj' },
	{ name: 'talerz', type: 'narysuj' },
	{ name: 'miska', type: 'narysuj' },
	{ name: 'myszka', type: 'narysuj' },
	{ name: 'papieros', type: 'narysuj' },
	{ name: 'fajka', type: 'narysuj' },
	{ name: 'buty', type: 'narysuj' },
	{ name: 'ręcznik', type: 'narysuj' },
	{ name: 'ser', type: 'narysuj' },
	{ name: 'deska do krojenia', type: 'narysuj' },
	{ name: 'lodówka', type: 'narysuj' },
	{ name: 'garnek', type: 'narysuj' },
	{ name: 'pudełko', type: 'narysuj' },
	{ name: 'opona', type: 'narysuj' },
	{ name: 'łódka', type: 'narysuj' },
	{ name: 'komin', type: 'narysuj' },
	{ name: 'pistolet', type: 'narysuj' },
	{ name: 'bomba', type: 'narysuj' },
	{ name: 'bomba atomowa', type: 'narysuj' },
	{ name: 'grzyb nuklearny', type: 'narysuj' },
	{ name: 'dynamit', type: 'narysuj' },
	{ name: 'granat', type: 'narysuj' },
	{ name: 'pocisk', type: 'narysuj' },
	{ name: 'puszka coca-coli', type: 'narysuj' },
	{ name: 'hantle (ciężarki)', type: 'narysuj' },
	{ name: 'głośnik', type: 'narysuj' },
	
	
	
]