
export default [
	{name: `Ada`, ext: '', val: 4, 'lat': 16, list: ['',''], tag: '', desc: '', type: 'sw-user'},
	{name: `Mela`, ext: '', val: 4, 'lat': 13.5, list: ['',''], tag: '', desc: '', type: 'sw-user'},
	{name: `Karol`, ext: '', val: 3, 'lat': 18, list: ['',''], tag: '', desc: '', type: 'sw-user'},
	{name: `Miki`, ext: '', val: 3, 'lat': 18, list: ['',''], tag: '', desc: '', type: 'sw-user'},
	{name: `Roksana`, ext: '', val: 3, 'lat': 16.6, list: ['',''], tag: '', desc: '', type: 'sw-user'},
	{name: `Nikita`, ext: '', val: 2, 'lat': 17, list: ['',''], tag: '', desc: '', type: 'sw-user'},
	{name: `Jacek`, ext: '', val: 3, 'lat': 12.7, list: ['',''], tag: '', desc: '', type: 'sw-user'},
	{name: `Alicja`, ext: '', val: 2, 'lat': 17.7, list: ['',''], tag: '', desc: '', type: 'sw-user'},
	{name: `Tomek`, ext: '', val: 2, 'lat': 13.7, list: ['',''], tag: '', desc: '', type: 'sw-user'},
	{name: `Michał`, ext: '', val: 2, 'lat': 12, list: ['',''], tag: '', desc: '', type: 'sw-user'},
	{name: `Kajtek`, ext: '', val: 2, 'lat': 13.4, list: ['',''], tag: '', desc: '', type: 'sw-user'},
	{name: `Olek`, ext: '', val: 2, 'lat': 15, list: ['',''], tag: '', desc: '', type: 'sw-user'},
	{name: `Kanonek`, ext: '', val: 2, 'lat': 15, list: ['',''], tag: '', desc: '', type: 'sw-user'},
	{name: `Blender`, ext: '', val: 3, 'lat': 16, list: ['',''], tag: '', desc: '', type: 'sw-user'},
	{name: `Zuzia`, ext: '', val: 2, 'lat': 14.3, list: ['',''], tag: '', desc: '', type: 'sw-user'},
	{name: `Julka`, ext: '', val: 2, 'lat': 11.4, list: ['',''], tag: '', desc: '', type: 'sw-user'},
	{name: `Żaba`, ext: '', val: 2, 'lat': 13.7, list: ['',''], tag: '', desc: '', type: 'sw-user'},
	{name: `Ola Meh`, ext: '', val: 3, 'lat': 13, list: ['',''], tag: '', desc: '', type: 'sw-user'},
	{name: `Nieznana`, ext: '', val: 2, 'lat': 13.3, list: ['',''], tag: '', desc: '', type: 'sw-user'},
	{name: `Eliza`, ext: '', val: 2, 'lat': 13.8, list: ['',''], tag: '', desc: '', type: 'sw-user'},
	{name: `Maja`, ext: '', val: 2, 'lat': 13.8, list: ['',''], tag: '', desc: '', type: 'sw-user'},
	{name: `Julka Dabrowska`, ext: '', val: 2, 'lat': 13.8, list: ['',''], tag: '', desc: '', type: 'sw-user'},
	{name: `Karolina Kisiel`, ext: '', val: 2, 'lat': 14, list: ['',''], tag: '', desc: '', type: 'sw-user'},
	{name: `Stasiu Kisiel`, ext: '', val: 2, 'lat': 12, list: ['',''], tag: '', desc: '', type: 'sw-user'},
	{name: `Maciej Stepan`, ext: '', val: 2, 'lat': 11.3, list: ['',''], tag: '', desc: '', type: 'sw-user'},
	{name: `Hubert Waśniewski`, ext: '', val: 2, 'lat': 12, list: ['',''], tag: '', desc: '', type: 'sw-user'},
	{name: `Ola`, ext: '', val: 2, 'lat': 13.6, list: ['',''], tag: '', desc: '', type: 'sw-user'},
	{name: `Oliwia`, ext: '', val: 2, 'lat': 14.1, list: ['',''], tag: '', desc: '', type: 'sw-user'},
	{name: `M.Kniż`, ext: '', val: 1, 'lat': 14.6, list: ['',''], tag: '', desc: '', type: 'sw-user'},
	{name: `A.Kniż`, ext: '', val: 1, 'lat': 12.8, list: ['',''], tag: '', desc: '', type: 'sw-user'},
	{name: `Amelka`, ext: '', val: 2, 'lat': 13, list: ['',''], tag: '', desc: '', type: 'sw-user'},
]